### ISSUE TITLE
Feature Request: Non-binary sensors

### ISSUE THREAD

**Issue by NeilDuToit92** [cgiesche/streamdeck-homeassistant#1]
I have tried to configure a text sensor. I see it is not on the list on the readme page, so I assume it isn't implemented yet?
I would like to be able to configure a button that just shows the the state of the entity - For example, I want to show a watts reading.

When I try to assign it, the button seems to get stuck on the previous entity. For example, I set it to a temperature entity, then try to set is to my watts entity, but it keeps showing the temperature entity in a 'frozen' state.

Thanks

Edit: Adding image of the entities
![image](https://user-images.githubusercontent.com/2218598/106645970-c388ff80-6595-11eb-9227-ceb180e331dc.png)

**Comment by cgiesche** [comment]
Could you please try this configuration for one of the above sensors?
![image](https://user-images.githubusercontent.com/5123180/106729975-5b2a3480-660e-11eb-89ca-a5ec1db8f91e.png)
If text sensors behave like nearly all other entities, this should at least display for example "100 W"

Please note: Due to a bug in StreamDeck UI, you are unable (at least i am with german keyboard layout) to enter curly braces {} into the text fields. You have to copy+paste them into the field -.-

{{state}} {{unit_of_measurement}}

**Comment by NeilDuToit92** [comment]
I will give that a try later today, I did try putting {{state}} in the title field, but not in the button line field, will see if it makes any difference.

**Comment by cgiesche** [comment]
I found a "maybe issue" in the code for unknown sensors that may be "workarounded" by overwriting the default labels. Getting stuck in the previous entities state should never happen, even with unknown sensors.
If the problem persists, i will try to reproduce (hardest part) and fix it.

**Comment by NeilDuToit92** [comment]
If the problem persists, I'll set up a 'helper' entity in HA to replicate and provide the steps here if that also reproduces the issue.
That should make it pretty simple for you to replicate.

**Comment by NeilDuToit92** [comment]
I just checked and I got it to work once, not sure how exactly.
Here are the steps of my testing. I use MQTT with auto discovery and a topic that publishes the latest Bitcoin price:

- Have MQTT configured in HA with auto discovery turned on
- Using MQTT Explorer, send the following:

Topic: `homeassistant/sensor/btc_test/ticker/config`
Message: `{
  "name": "btc_test",
  "unit_of_meas": "$",
  "stat_t": "btc_test/ticker",
  "dev": {
    "mf": "BTC",
    "mdl": "BTC",
    "ids": [
      "BTC"
    ],
    "name": "BTC",
    "sw": "5"
  }
}`

Topic: `btc_test/ticker`
Message: `35000`


- On StreamDeck - Add buttons with Domain as 'sensor' and Entity as 'btc_test'

1. Just save without changing anything else -  Shows gray HA logo, no data
2. Enable custom title and set it to `{{state}}`  -  Shows gray HA logo, no data
3. Enable custom labels and set line 1 to `{{state}}`  -  Shows gray HA logo, no data
4. Do both 3 and 4  -  Shows gray HA logo, no data

**Comment by cgiesche** [comment]
Thank you very much for this perfectly prepared instructions!

"Bad" news: It works for me!?
![image](https://user-images.githubusercontent.com/5123180/106801990-aa9a5000-6662-11eb-9603-520423c124bf.png)
![image](https://user-images.githubusercontent.com/5123180/106802032-b84fd580-6662-11eb-9bfc-843014e3f4fc.png)
![image](https://user-images.githubusercontent.com/5123180/106802054-bdad2000-6662-11eb-84e9-7d8d90c6e2ce.png)
![image](https://user-images.githubusercontent.com/5123180/106802081-c271d400-6662-11eb-943c-0a3621792f81.png)

I will try to break it somehow :D

**Comment by cgiesche** [comment]
Ok, that fix destroyed something else. Stay tuned.
