### ISSUE TITLE
Release schedule? 

### ISSUE THREAD

**Issue by Tmacmannis** [cgiesche/streamdeck-homeassistant#102]
Sorry for the beginner question but is there a way to get the latest build or do I have to wait for the next release? See a cool fix to remove the button icon I was hoping to try out. Thanks!

**Comment by cgiesche** [comment]
Hi, i am planning the next release for around 1. of july.
As there seem to be no further changes until then, i have created a pre-release that can be downloaded here:
https://github.com/cgiesche/streamdeck-homeassistant/releases/tag/2.1.0

I am not sure, if there will be problems with future auto-updates via the store, if you install this release manually. So use at your own risk ;)

**Comment by Tmacmannis** [comment]
Working perfectly, thank you!
