### ISSUE TITLE
Enable service call on sensor entity

### ISSUE THREAD

**Issue by dioneimiodutzki** [cgiesche/streamdeck-homeassistant#103]
Hello, would it be possible to include a service call option even when a sensor is selected as entity?
I have today a button with the temperature and another with the humidity, both working fine. 
I would like to add a service call to power on/off the AC on the temperatue one, and power on/off the humidifier in the humidity one.
The entities used on the service call would be other ones than the sensor ones (I think this is already supported in the payload json).

Thanks!

**Comment by cgiesche** [comment]
I am working on this feature. You will be able to independently select entity for display and services (+entities) for short- and longpress.

**Comment by humbertogontijo** [comment]
Any progress?

**Comment by humbertogontijo** [comment]
Yes, it worked nicely! Thank you
One extra comment, the domains and services drop down could be sorted alphabetically, but not a big deal

**Comment by cgiesche** [comment]
Should be fixed in upcoming release ([2.3.1](https://github.com/cgiesche/streamdeck-homeassistant/releases/tag/2.3.1)). Will be deployed to elgato store soon.

(Sorting did not get in yet :( )
