### ISSUE TITLE
Readme example code for multiple entities missing a comma

### ISSUE THREAD

**Issue by static418** [cgiesche/streamdeck-homeassistant#104]
Hi,
I promise my intention isn't to be pedantic, but I literally, however that reflects on me, spent 20ish minutes troubleshooting this yesterday.  In the readme, the following example is given to add service data that includes acting on multiple HASS entities:

`
{
  "entity_id": [
    "switch.osram_plug_01_bac00b0a_on_off",
    "switch.osram_plug_01_87c00a0a_on_off"
  ]
  "brightness": 120,
  "rgb_color": [255, 0, 0]
}`

Without adding a comma after the bracket at the end of the entity list, JSON validation fails.  The validated snippet would be:

`
{
  "entity_id": [
    "switch.osram_plug_01_bac00b0a_on_off",
    "switch.osram_plug_01_87c00a0a_on_off"
  ],
  "brightness": 120,
  "rgb_color": [255, 0, 0]
}
`
I'm not super familiar with github or I'd make the PR myself, but I have no doubt that this is nothing more than a typo that everyone but me knew how to fix already.  Thanks for everything else, the plugin works fantastically!

**Comment by cgiesche** [comment]
Hi,

thanks for your message and sorry for your wasted 20 minutes ;). I will fix the documentation :)
