### ISSUE TITLE
Icons overlap the informations

### ISSUE THREAD

**Issue by andrewbpowers** [cgiesche/streamdeck-homeassistant#106]
Hello!

In the examples you can see how an icon/graphic (e.g. a phone, thermometer, etc.) is displayed, then below it the value of the sensor and then the description of the measuring point. 

No matter which icon I use, it always covers the text/measurement values. Only what is in the (custom) button title is displayed above the icon.

So how have the examples been implemented?

Thanks for any help and tips in advance!
:-)

**Comment by cgiesche** [comment]
Hi,

one of the disadvantages of the "custom icon" button ist, that (due to technical restrictions) values cannot be rendered on top of the icon. All of the example icons use the "generic" Entity.

![image](https://user-images.githubusercontent.com/5123180/191926880-ca7bc3cd-b15e-4e78-bbf3-5698494fedb0.png)

**Comment by andrewbpowers** [comment]
Thank you for the feedback!

**Comment by andrewbpowers** [comment]
Entity (generic) -> Domain: Sensor -> Entity: temperature_bmw280 = Temperature is displayed at the top and the title at the bottom

Entity (generic) -> Domain: Sensor -> Entity: temperature_bmw280 + An icon form the Stream Deck Library = only the title at the bottom displayed :-(

**Comment by andrewbpowers** [comment]
Thanks!

Then it would be useful if you could tell us how you realized your examples. ;-)

**Comment by cgiesche** [comment]
Oops, lost track of your question. I thin you may have worked this out already, but here is an example:

![image](https://github.com/cgiesche/streamdeck-homeassistant/assets/5123180/13815549-1d58-45bc-bfd2-0c8e982531be)

![image](https://github.com/cgiesche/streamdeck-homeassistant/assets/5123180/e34723f3-b7c7-472f-b9e9-a0a1bc1bda88)

(\&#37; is a workaround for the non-working percent characters)

**Comment by andrewbpowers** [comment]
No problem! ;-)

Thank you very much and have a great day!
