### ISSUE TITLE
Light brightness control?

### ISSUE THREAD

**Issue by mihalski** [cgiesche/streamdeck-homeassistant#107]
Hi,

Thank you for an awesome plugin.
Is it possible to incrementally increase/decrease the brightness of a light?
If so what would the service data JSON look like?

Regards,
Michal

**Comment by TarheelGrad1998** [comment]
I have a similar request for climate, to be able to adjust the setpoint.  It seems that templates are not currently supported within the JSON?  

E.g. the using following with set_temperature does not work

{
"temperature":"{{ temperature + 1 }}"
}

**Comment by bensmithuk** [comment]
For lights I use {"brightness_step_pct":"+20"}

**Comment by AaronAutomation** [comment]
> For lights I use {"brightness_step_pct":"+20"}

Confirmed this works. Setting the Domain to a light with the service 'turn_on' and adding the above text to the Service Data JSON yields the expected results. Using '-' (with service 'turn_on'still) dims the lights the desired amount all the way to 0 as well. Thanks.
