### ISSUE TITLE
Allow URL actions on button click

### ISSUE THREAD

**Issue by pedropombeiro** [cgiesche/streamdeck-homeassistant#112]
Some buttons could have useful actions associated with them. For instance, a button showing a person location could open the Google Maps page showing that person's location when clicked on the Stream Deck. For that, we would need to add a `url_action` field that contains a URL action that would be executed by the plugin when clicked. Example of the URL: `https://www.google.com/maps/place/{{ state_attr('device_tracker.my_phone', 'latitude') }},{{ state_attr('device_tracker.my_phone', 'longitude') }}`.

**Comment by kineticscreen** [comment]
Yeah, this feels like part of a broader feature set which would be good, which would be just more customatisation of button actions. For example, it would be really great if the Entity Toggle could have the option of setting different actions for on and off. Essentially separating what the button displays, from what actions pressing it take.

**Comment by cgiesche** [comment]
@kineticscreen I am working on exactly what you describe: https://github.com/cgiesche/streamdeck-homeassistant/issues/103
@pedropombeiro I am not planning to implement your feature suggestion as it would work completely different compared to current service calls. :(
