### ISSUE TITLE
Sensor values don't update

### ISSUE THREAD

**Issue by GeorgeDouglasMcFly** [cgiesche/streamdeck-homeassistant#113]
Hello all,

first of all thank you for this great plugin.

I noticed one problem: The values of my sensors do not update. How often does this plugin synchronize?

![Example](https://user-images.githubusercontent.com/62904800/203287115-6c4f261d-dc2e-46ec-9a18-0d395f85e6c8.png)

Best regards

**Comment by GeorgeDouglasMcFly** [comment]
Okay, sorry, there was an issue in my configuration.

**Comment by vasuncion** [comment]
My sensor is updating on HA but not on streamdeck

![image](https://github.com/cgiesche/streamdeck-homeassistant/assets/92342789/5bf4f808-4906-43b2-94a0-874c123c3ee0)
