### ISSUE TITLE
"Failed to Connect" yields illegal constructor errors upon inspection

### ISSUE THREAD

**Issue by jeremyfuksa** [cgiesche/streamdeck-homeassistant#116]
Stream Deck v6.0.1 (17722)
Plugin v2.0.1

I'm getting connection failures in the plugin. I have turned on debugging in Stream Deck and have analyzed the output. I've found:
```
[Error] TypeError: Illegal constructor
	CSSStyleSheet (Images.js:4)
	Module Code (Images.js:4)
	...
```
The illegal constructor in images.js is `const sheet = new CSSStyleSheet();`

Thoughts as to how this breaks the plugin?

**Comment by cgiesche** [comment]
Hi,

sorry for the late reply:
The error you are seeing in yor logs seems not to be related to my plugin. I am not using a class called "CSSStyleSheet".

Often, connection issues are related to the URL or an invalid token:
If your Home-Assistant is secured by a **valid** SSL certificate, the url should look like this:
`wss://ip_or_domain_of_your_home_assistant:port/api/websocket`
Without SSL:
`ws://ip_or_domain_of_your_home_assistant:port/api/websocket`

For example:
`wss://myhomeassistant.com:1234/api/websocket`
or
`ws://192.168.1.100:1234/api/websocket`

Please note that self-signed-certificates are not supported (and can not be supported).
