### ISSUE TITLE
Use jinja templating: substring?

### ISSUE THREAD

**Issue by wivaku** [cgiesche/streamdeck-homeassistant#118]
Love the functionality.
Would like to use something like this as my custom label for e.g. my `media_player` entity:

```
{{ media_title[0:13] }}
{{ media_title[13:26] }}
```

This so I can split the title in 2 lines.

Similar to:
```
{{ state_attr("media_player.homepod","media_title")[0:13] }}
{{ state_attr("media_player.homepod","media_title")[13:26] }}
```

I was hoping this was possible because of #11  but it does not seem to work.

**Comment by cgiesche** [comment]
Hi,

the `slice` function should work:
`
{{ media_title.slice(0,13) }}
{{ media_title.slice(13,26) }}
`

https://mozilla.github.io/nunjucks/templating.html#slice

**Comment by wivaku** [comment]
That's great, thanks @cgiesche!
I have added `if ...` so it also works if the attribute has no value.

Really happy with how I can now split title and artist each in two rows:

```
{{media_title.slice(0,12) if media_title}}
{{media_title.slice(12,24) if media_title}}
{{media_artist.slice(0,12) if media_artist}}
{{media_artist.slice(12,24) if media_artist}}
```

BTW I also tried adding `.trim()` (to delete any leading whitespace) but that did not have any effect.
