### ISSUE TITLE
Possible to change font size of sensor state and remove icon?

### ISSUE THREAD

**Issue by fragande** [cgiesche/streamdeck-homeassistant#119]
As topic states, I'm wondering if this is possible (or it's a feature request).

The fixed font size is painfully small when showing sensor state, and a lot of space is taken up by the icon. Example:

![bild](https://user-images.githubusercontent.com/24630657/208221310-3c345cc0-bcbe-47ec-a479-b2bbb9868382.png)

In this case I would like for the state to be as large as possible, while still fitting within the button, and a very small descriptor above or beneath. I know I could lose the unit of measurement in this example, but that doesn't increase the font size of the state so I just filled up the otherwise empty space (otherwise it looks ridiculous 😄):

![bild](https://user-images.githubusercontent.com/24630657/208221739-36bcc81d-c0e3-4638-aa36-6d4105e9420a.png)

**Comment by cgiesche** [comment]
I am not yet planning to implement this as a feature, but with the newest version from the store you can accomplish a look close to what you want:

![image](https://user-images.githubusercontent.com/5123180/216079033-a90fc98d-800a-46db-8d53-25e97e8b5a90.png)

Steps to get this result:
* Clear title field
* Check "Hide icon" option
  ![image](https://user-images.githubusercontent.com/5123180/216079143-1932faf9-2a38-47c0-939b-8fc804b5cfa3.png)
* Enable "Custom title" and enter template
  ![image](https://user-images.githubusercontent.com/5123180/216079320-8c7caacc-7635-4729-bdd8-0998b2013afd.png)
* Enable "Custom labels" an enter a single space
![image](https://user-images.githubusercontent.com/5123180/216079733-5ca163e5-cdbf-40ce-b734-4d42abcf30c7.png)
* Adjust font position and size for your custom title
   ![image](https://user-images.githubusercontent.com/5123180/216079896-ba4cd8e6-5d60-4899-bd23-f5a1046d1843.png)

Yes, it is a dirty solution, but it works :D

**Comment by fragande** [comment]
> Yes, it is a dirty solution, but it works :D

Thank you! Yes, it's a huge improvement for sure, now it's actually readable from a normal distance 😄Good enough for me.

 
![bild](https://user-images.githubusercontent.com/24630657/216082925-fbacbcbd-015c-477d-97fb-576380692083.png)

**Comment by gaborbernat** [comment]
Any way to alter the font size of the labels?

**Comment by cgiesche** [comment]
Short answer: No.
This would be very complicated to implement for a one-man-show ;)
