### ISSUE TITLE
How to specify Service Data

### ISSUE THREAD

**Issue by rklueber** [cgiesche/streamdeck-homeassistant#12]
I am not sure if I get the full concept. Yet. Toggling a light or turning it on/off works.  

I miss the possibility to specify service data for a more complex service. Think of `climate` and `set_preset_mode`. I would like to specify the mode like 
`{
  "entity_id": "climate.temperatur_arbeiten", 
  "preset_mode": "comfort" 
}
`

Am I missing something?

**Comment by cgiesche** [comment]
Hi,

it is currently not possible to add payload to a service call but I would like to add this option. Unfortunatelly i do not know what is needed exactly. An easy option would be to allow to enter a static service call payload that will be sent every time the button is pressed.

If there is a need to have "dynamic" parts inside the payload (for example values from the current state), things would quickly get more complicated.

**Comment by cgiesche** [comment]
New issue for static payload: #13
