### ISSUE TITLE
How to show '%' in custom labels?

### ISSUE THREAD

**Issue by kchiem** [cgiesche/streamdeck-homeassistant#120]
It used to be that I could do something like:

`{{humidity}}%`

But now, that results in a blank home assistant icon.  If I remove the `%`, it shows the humidity.  How do I get the percent symbol in there now?

**Comment by aaronr8684** [comment]
`{{humidity + '%'}}` should do the trick

**Comment by cgiesche** [comment]
It seems like something changed in the new StreamDeck version which causes the '%'-Character to "crash" the plugin. I am not yet sure where and why the problem occurs. (Input field of my plugin / the storage where StreamDeck stores it's configuration / SVG rendering).

I was not able to find any workaround for displaying '%' correctly....

**Comment by kchiem** [comment]
> `{{humidity + '%'}}` should do the trick

Doesn't work.

**Comment by cgiesche** [comment]
Closed as duplicate of #114
