### ISSUE TITLE
Missing "notif" domain, probably need a "Service" button

### ISSUE THREAD

**Issue by MarlBurroW** [cgiesche/streamdeck-homeassistant#122]
The `notif `domain is not available from the "Domain" dropdown.

Availables domains seems to be mapped from entities states: Visible here https://github.com/cgiesche/streamdeck-homeassistant/blob/master/src/PiComponent.vue#L360

The probleme is there is no entities/states for the `notif` domain, so this domain is not retrieved and pushed in the `availableDomains ` array.

You can mannualy push the domain  (like [homeassistant](https://github.com/cgiesche/streamdeck-homeassistant/blob/master/src/PiComponent.vue#L367)).
```js
this.availableDomains.push("notif");
```
But I suppose the Entities dropdown will be empty because notif domain includes only services.

I think the best way to handle notifications from streamdeck is to add a "Service" button in the palette.

**Comment by cgiesche** [comment]
Mhm mhm mhm, i understand. A dedicated "service" button sounds interesting.

**Comment by MarlBurroW** [comment]
A good example for this feature is the home assistant plugin for Nodered.
The service node allow to select the domain, the service name, then add a JSON payload to send.

![image](https://i.imgur.com/VBPlFLZ.png)
