### ISSUE TITLE
Missing "webostv" domain

### ISSUE THREAD

**Issue by bawitdaba** [cgiesche/streamdeck-homeassistant#125]
I use the HA integration "LG webOS Smart TV" and I'm missing the webostv domain using the streamdeck plugin.

I used to use the old HA plugin for streamdeck https://github.com/tobimori/streamdeck-homeassistant which let me free-form enter the domain, but this plugin is no longer supported on streamdeck 6.x

In the old plugin I would specify the following

url and token
Service Domain: webostv
Service: command
Service Data: {"entity_id":"media_player.lg_office_tv", "command":"system/turnOff"}

I have various buttons for on, off, vol up, down, and HDMI inputs....

Any suggestions on how to make this work? I tried different domains that were selectable such as mediaplayer domain and homeassistant domains and neither of those worked

**Comment by cgiesche** [comment]
I am working on a more or less complete rework on how domains, entities and services are working in the plugin. I guess after that, your "webostv" domain will automatically show up (as my "hue" domain does).

**Comment by bawitdaba** [comment]
> I am working on a more or less complete rework on how domains, entities and services are working in the plugin. I guess after that, your "webostv" domain will automatically show up (as my "hue" domain does).

Thank you!

**Comment by cgiesche** [comment]
Already fixed, as i remember ;)

**Comment by cgiesche** [comment]
I was wrong.

**Comment by EpicLPer** [comment]
Just want to come by and say that I also miss services/domains like "spotcast" as example, thanks already for working on this! Awesome addon :)
