### ISSUE TITLE
Constant green checkmarks on XL + 6.x.x

### ISSUE THREAD

**Issue by arthurEspooner** [cgiesche/streamdeck-homeassistant#126]
set up a stream deck XL and upgraded both it and my 15 key to 6.x.x

the XL is constantly showing the green check marks over the icon. i can't establish any rhyme or reason for the behavior yet. i have to switch to another page then back to clear them.

doesn't happen at all on the 15 key.

**Comment by ad314159** [comment]
Same issue occurs for me.  

On initial connection, it remains on screen. It disappears once the button is pressed. 

I also have the 15 button deck running the latest software.

**Comment by arthurEspooner** [comment]
interesting, i've never seen it on my 15 key which i've been using for a few months. i'm doing some more testing with only 1 plugged in at a time.

**Comment by arthurEspooner** [comment]
still have not seen it happen on the 15 key. the XL seems to have issues, not sure if this is related to v6 as i upgraded the XL as soon as i got it. i tried dedicated usb to rule out power and simplified the profile and it still happens randomly. if i let the XL sit for a few hours and come back i also need to restart the stream deck app or it throws the yellow error icon. i've used the 15 key for ~3 months without any of these issues.

**Comment by arthurEspooner** [comment]
downgraded to 5.3.3 via [this guide](https://help.elgato.com/hc/en-us/articles/10743096095373-Stream-Deck-6-0-and-Plugin-Compatibility) and all is well again. i'll be holding off a while until v6 is more stable as i had issues with other plugins as well.

**Comment by kineticscreen** [comment]
I have this green check mark only on one of my buttons - an entity with a serve call to fire a an IR remote function.
All other home assistant buttons on my streamdeck do not exhibit this.

**Comment by jtenniswood** [comment]
I have this happen as well. It happens when you have devices but not automations or scenes. It looks like it checks the state of them. It's pretty annoying would be good to fix.

**Comment by arthurEspooner** [comment]
it looks like the recent 6.1 release fixes this, i will not be trying it though. since #128 was fixed i'm not having any major issues on 5.x mk2 or xl with latest 2.2.0 for this plugin. i value stability over whatever silly things they are adding in these updates that break too many things.

if someone can verify 6.1 fixes this it could be closed as it's not really on @cgiesche side.

**Comment by kineticscreen** [comment]
Still doing it for me on 6.1

**Comment by ggflempire** [comment]
Same here. 15 button stream deck, newest update on both app and firmware..
