### ISSUE TITLE
delay in status change

### ISSUE THREAD

**Issue by ifuchs** [cgiesche/streamdeck-homeassistant#127]
This works fine with the only reservation being that when I toggle a switch, it happens immediately but only shows up as changed on the Streamdeck after about 10sec. Is that normal?

**Comment by cgiesche** [comment]
The plugin itself is stateless. It always displays the status it last received from Home-Assistant. When a switch is pressed, the plugin only sends the switch command to Home-Assistant. Normally, when the switch is successfully switched, Home-Assistant sends the new status of the switch back to the plugin, which then displays it. For me, all this happens in less than 500ms. Depending on the integration used in Home-Assistant, it may take longer. You might want to check in the Home-Assistant GUI when the corresponding switch "switches" while you are switching it.

**Comment by ifuchs** [comment]
Thanks for the clarification and suggestion. I think that the switch I was using to test is an Emporia switch and it may be going to the server and back before HA sees the change. Clearly, not related to the plug-in.
