### ISSUE TITLE
high memory usage

### ISSUE THREAD

**Issue by arthurEspooner** [cgiesche/streamdeck-homeassistant#128]
while doing testing for #126 i realized that this plugin was using a lot of memory after a few hours. i couldn't figure out if a specific button was doing it, or the fact i had 32 buttons at one time on an XL using this plugin. these are various sensors and media controls. memory usage will climb over the course of a few hours and i've seen it as high as 40(!) GB.

i've had this plugin uninstalled for 2 days now and this is not happening. i'm going to do some more testing to see if it was a specific entity/etc causing it.

**Comment by arthurEspooner** [comment]
i reinstalled the HA plugin and readded about a 1/3 of the overall buttons i was using with it. i made it as basic as possible, no custom calls or even icons. it's been solid for 2 days now, no disconnects, instant response, and also no #126

**Comment by arthurEspooner** [comment]
spoke too soon, it's back now with same behavior. commands are delayed, resource usage is high, then eventually it stops responding while resource usage keeps climbing until you close steam deck.

shame, guess i need to restart the stream deck app hourly via a script or something. seems like multiple people are having these problems spread across a few different issues.

**Comment by cgiesche** [comment]
Hmpf. I will add 20 fast updating sensors and see what happens...

**Comment by cgiesche** [comment]
F***
![image](https://user-images.githubusercontent.com/5123180/214601304-cc3cc0ec-7a7e-4a8f-8fdd-ebcbdf510a58.png)
few seconds later
![image](https://user-images.githubusercontent.com/5123180/214601650-cfb93227-3c0f-437a-831c-2243869e7449.png)

**Comment by cgiesche** [comment]
I found the memory leak and fixed it.

**Comment by cgiesche** [comment]
@arthurEspooner A new release (https://github.com/cgiesche/streamdeck-homeassistant/releases/tag/2.2.0) is on its way to the elgato store. Maybe you want to install the version directly to check if some of your issues are fixed.

(I noticed that memory usage is still high(er) than normal if you have connected debugger or chrome dev tools but this seems to be ok, as memory usage goes back to normal as soon as dev tools are closed.)

**Comment by arthurEspooner** [comment]
yep, it's fixed, thank you! i wasn't following this and since plugins auto-update i didn't realize this got deployed. i haven't seen this for a few weeks though and i was checking consistently.
