### ISSUE TITLE
Allow to add static payload to service call

### ISSUE THREAD

**Issue by cgiesche** [cgiesche/streamdeck-homeassistant#13]
- If an action is selected in PI, show text-field that allows to add payload for service call
- Validate if payload is valid JSON before saving
- Send payload when performing service call

**Comment by rklueber** [comment]
Static payload would already give a lot more options. 

You might want to look here how it was done. 

https://github.com/tobimori/streamdeck-homeassistant

a non static solution might be based on the templating engine as well.
