### ISSUE TITLE
Home Assistant Addon doesn't install from the Plugins store.

### ISSUE THREAD

**Issue by ImaBadCoder** [cgiesche/streamdeck-homeassistant#134]
I transitioned computers and now I am not able to install the Home Assistant StreamDeck Addon.  Says it is installing, but I close and reopen and it shows as not installed. I am able to install other plugins without issue. Is anyone else having this issue?

thanks

**Comment by Jfulks2021** [comment]
I'm having the same problem, but im not using a new install, the addon just kind of Uninstalled itself and I can't get the adding installed again, I even did a add remove programs on elgotto, reinstalled it, and still have this problem, I was thinking maybe my pc got a virus, dispite no other issues, and was about to reimage my pc when I seen this post.

**Comment by cgiesche** [comment]
O_o

Oh no. I will check...

**Comment by ImaBadCoder** [comment]
What information is needed to troubleshoot this issue?

**Comment by ImaBadCoder** [comment]
I was able to get this working again. I uninstalled the streamlabs app, removed all the folders associated with elgado from %ProgramData% and %appData%.. There were a few, make sure to check all the sub folders for Local, LocalLow, and Roaming. Then I reinstalled the app and it worked. I think there was a folder that kept the install from working. I came to this conclusion by downloading the plugin directly from github. Once I did this, I got a message saying that the plugin is already installed, which prompted me to remove any existing folders and start from scratch.. Good news is that I am working now, just need setup the other pieces again.

**Comment by cgiesche** [comment]
Great to hear, this worked for you. I am constantly installing, uninstalling and on-the-fly-exchanging the plugin during development, so it is very hard for me to find out, what happens during an automatic upgrade via store or fresh installs.
Lucky me, this time. @Jfulks2021 Maybe the solution from https://github.com/cgiesche/streamdeck-homeassistant/issues/134#issuecomment-1430119972 works for you, too?

**Comment by Jfulks2021** [comment]
@ImaBadCoder thanks worked perfectly,
@cgiesche mine worked just like ImaBadCoders did
Thanks for the help, too bad I lost my entire setup, but I'll rebuild it. Just glad it's working again
