### ISSUE TITLE
PC Sleep Loses Connection with Home-Assistant Plugin

### ISSUE THREAD

**Issue by Poncho42** [cgiesche/streamdeck-homeassistant#142]
Hey there, love the plugin its working wonderfully for me, except one issue. 

When my PC goes to sleep and wakes back up, home assistant integration, more times than not, cannot process the commands.

I get a yellow triangle with an '!'

When I restart the stream deck app entirely it seems to fix the problem. I know troubleshooting things that happen during sleep is a really hard process, but if you could look into it, that would be great!

Stream Deck XL Firmware 1.01.000
Stream Deck Software 6.1.0.18521
Windows 11 22H2 (OS Build 22621.1413)

**Comment by cgiesche** [comment]
Hi @Poncho42 

thanks for you report. This issue is a good old friend of mine (https://github.com/cgiesche/streamdeck-homeassistant/issues/92). In the upcoming update (soon™) i fixed a "smelly" code point related to the Home-Assistant connection that MAY have lead to this issue.

**Comment by Poncho42** [comment]
Amazing! Sorry for the double post then! Again, amazing work for this I use it all the time in my wfh office

Sent from my T-Mobile 5G Device
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by anthonyma94** [comment]
Sorry to necro this, I recently did a factory reset from Windows 10 to 11, and the plugin is experiencing this behaviour. I actually use wss even in my local network by default, so #92 was not the issue. I've even tried to use ws://localIP:8123, same issue.
