### ISSUE TITLE
Slow Response 

### ISSUE THREAD

**Issue by RamblingGeekUK** [cgiesche/streamdeck-homeassistant#147]
Does anyone else experience slow or delayed responses when using the HA Plugin?  I can switch to the profile, tap a button to turn a light on and it can sit there for around 10 seconds before doing it, sometimes it's instant.   Its odd, not sure if its a plugin or Streamdeck software

**Comment by applegeeks** [comment]
first time owner of streamdeck but longtime HA enthusiast.
setup it up this week with the plugin and not seeing any slow response you seem to be experiencing.

my HA setup is on a baremetal mini pc though using the HAOS.

**Comment by RamblingGeekUK** [comment]
it's odd.  I'll close this issue as I don't think it's the plugin.  Thanks!

**Comment by RamblingGeekUK** [comment]
This is the delay, I'm getting.   Only the HA plug-in does this on 4 stream decks, plugged into a StarCom dedicated USB port for each StreamDeck,  I have updated it to 2.3.0.   I think things go worst when I change the icon from the default. 

https://github.com/cgiesche/streamdeck-homeassistant/assets/7108949/6446aac0-fc3f-4bce-a6a5-bdb07101f699

**Comment by RamblingGeekUK** [comment]
When just have one button it's fine... do I have too many ?  Is there a limit?

**Comment by cgiesche** [comment]
I don't think there is a button limit. But depending on how the stream-deck software is working internally, many buttons may slow down the whole application.
From inside my plugin, i can not really improve the performance :(
