### ISSUE TITLE
Cloud based Authentication

### ISSUE THREAD

**Issue by LitlNickyScarfo** [cgiesche/streamdeck-homeassistant#149]
I've tried several ways to get my streamdeck to connect as it's not on my native LAN, but on a separate VLAN. I've tried to use Nabu Casa Url with various formats without success.

Can you provide an example to use?

**Comment by cgiesche** [comment]
Sorry, i have no experience with nabu casa and did not find anything helpful on the web:
The plugin needs access to the home assistant websocket URL. It is very likely that this URL is not public accessible when you are using nabu casa.

**Comment by cgiesche** [comment]
Maybe it works with nabu casa: #181 (not yet verified)
