### ISSUE TITLE
Sensor Number Not Showing

### ISSUE THREAD

**Issue by MattMake** [cgiesche/streamdeck-homeassistant#151]
Please, this could completely be user error, so I apologize in advance if that is the case.

I'm configuring HA sensor values into StreamDeck buttons.   They show for all that I am providing, except for one.

I have Powerwall Solar Now, Load Now, PW Now and Grid Export showing properly.  However, when I attempt to show the Powerwall charge, I just get the HA icon with no values.  Powerwall charge provides a percentage number, where the others provide kW.

Any thoughts?

**Comment by MattMake** [comment]
![image](https://user-images.githubusercontent.com/39313738/235938141-7a9cdf70-a686-4930-94cd-cff6fa59ef96.png)

**Comment by MattMake** [comment]
The % sensor is top right.

**Comment by DarkPaladin3** [comment]
It is the % that messes it up. If the {{state}} has the number portion of the title and {{unit_of_measurement}} holds the "%" sign then you need to use the formatting below to get the "%" to show up. 

{{state}} {{ unit_of_measurement | urlencode }}

If you don't have {{ unit_of_measurement }} the use,

{{state}} {{ "%" | urlencode }}

Hope that helps.

**Comment by MattMake** [comment]
Thanks @DarkPaladin3, I can understand the issue.  I set the states in the custom label and it worked as you suggested.  Best presentation in my instance was '{{state}}{{ "%"}}'
