### ISSUE TITLE
Cant paste into HA url or access-token

### ISSUE THREAD

**Issue by magicman32** [cgiesche/streamdeck-homeassistant#152]
Cant paste into HA url or access-token

I have uninstalled and re-installed plugin at least 6 times
I have even tried typing access token in manually, but with such a long code, Im sure I got it wrong each time

One of the main reasons for getting stream deck was for home assistant pluging features, help please

**Comment by cgiesche** [comment]
Hi,

as context-menus are disabled in the streamdeck software, you can only past into the text fields by pressing CTRL+V.

![CopyPaste](https://github.com/cgiesche/streamdeck-homeassistant/assets/5123180/c4f839ce-47be-46d4-ac49-3c9e9168cfa0)

**Comment by magicman32** [comment]
Thank you so much for that info, I thought I was doing something wrong lol
