### ISSUE TITLE
Elgato Stream Deck - Plugin not installing

### ISSUE THREAD

**Issue by str8player** [cgiesche/streamdeck-homeassistant#156]
The plugin has been working great up until a few days ago. It shows installing but when I go to the plugin area it is not there. When I go back to the plugins store, it shows not installed. I have installed other plugins since and they work fine.

**Comment by str8player** [comment]
That is exactly what mine looks like

**Comment by jcallaghan** [comment]
I reviewed my installed Plugins today and noticed the Home Assistant plugin was uninstalled even though it was installed yesterday. Will continue to explore why this is happening.

![image](https://github.com/cgiesche/streamdeck-homeassistant/assets/7449908/647d51b2-57c9-4be3-94be-52fc203d198f)

**Comment by jcallaghan** [comment]
Okay. Dug around a little deeper and I've managed to get this plugin working again. For how long I don't know. 

Repo steps.

1. Installing this plugin via Stream Deck store.
2. Go back to the Store and it shows and uninstalled and offers for it to be installed again.
3. Browse to ```C:\Users\User\AppData\Roaming\Elgato\StreamDeck\Plugins```.
4. Remove the ```de.perdoctus.streamdeck.homeassistant.sdPlugin``` directory.
5. Go to this projects [releases page](https://github.com/cgiesche/streamdeck-homeassistant/releases) and download ```de.perdoctus.streamdeck.homeassistant```.
6. Install the downloaded plugin.

Fingers crossed this works for you too @str8player.

**Comment by ironboy1** [comment]
@jcallaghan thanks for providing the workaround, made my day and my stream deck home assistant interaction working again 😊

**Comment by str8player** [comment]
@jcallaghan This worked for me too. Thank you!

**Comment by cgiesche** [comment]
I have no idea why this happened. The installation process is handled by elgato/streamdeck.
Please let me know if this issue still occurs.
