### ISSUE TITLE
Feature Requests - Trigger Streamdeck Button From Home Assistant 

### ISSUE THREAD

**Issue by x-luthor** [cgiesche/streamdeck-homeassistant#158]
Hi There,

Is it possible to do the reverse of what this plugin provides? Allowing home assistant to trigger a Streamdeck button?

Ex - I would like to create an Automation in Home assistant that will trigger a streamdeck button (run a macro, hotkey, etc) when run. Or, I just want to create a button in Home assistant that will trigger Streamdeck button page 1 button 1.

Is this functionality possible?

Thanks

**Comment by cgiesche** [comment]
Hi,

this is not possible due to technical limitations. A plugin can not access any other plugins (i think for security reasos). :(
