### ISSUE TITLE
Entities are lost when exporting profile

### ISSUE THREAD

**Issue by LewisSpring** [cgiesche/streamdeck-homeassistant#164]
Hello,
I exported my Steam Deck profiles so I could reinstall Windows on a new SSD, but found that the configuration for each button is lost in the exported profile. 

Even re-adding my server, the buttons have not kept their settings and just show up as “Entity”. The options to connect to the server are there, but not the settings for the entity itself. 

I still have the original install available. 

Cheers

**Comment by djripcord** [comment]
I only seem to have this problem if my Home Assistant Server URL is incorrect.

In my case, I omitted a decimal for one of the IP address octets. But I never got a "unable to connect" error when this occurred.
