### ISSUE TITLE
pressing buttons on StreamDeck does not have any response

### ISSUE THREAD

**Issue by corey072** [cgiesche/streamdeck-homeassistant#170]
HELLO..How can I control my Home Assistant switch devices on StreamDeck? I have connected Home Assistant successfully, but pressing buttons on StreamDeck does not have any response. However, I can see the status of the devices on StreamDeck when I switch them on or off using Home Assistant. Do you have any suggestions?

**Comment by cgiesche** [comment]
Hi,

the configuration is divided into two parts:
1. "Display Settings" (What should be visible on the button)
2. "Button Settings" (What sould happen if you press the button)

This only shows the current state of the Büro light entity:
![image](https://github.com/cgiesche/streamdeck-homeassistant/assets/5123180/9abd9b83-e374-4541-951f-e55590a203f7)

This makes the button call a service when it is pressed:
![image](https://github.com/cgiesche/streamdeck-homeassistant/assets/5123180/fcf585e3-4098-4427-ba1f-46142301d875)
