### ISSUE TITLE
Feature Request: Change Colors / Transparency

### ISSUE THREAD

**Issue by noctividus** [cgiesche/streamdeck-homeassistant#173]
It would be cool if we could change the background color based on a state. For instance {{state}},{{button_bg: red}}

**Comment by xXAzazelXx** [comment]
Yes, please! I would love to be able to change the background or even better to set an icon in the background

**Comment by noctividus** [comment]
I came back because I figured out how to do this with existing features.

First, figure out which variable holds the state you want to look at. These can be found in the $(Variables) tab right next to the presets. Click the blue Home Assistant Button. My variable for hallway motion looked like this, but that page has every variable available to you.

$(homeassistant-server:entity.binary_sensor.zone_5.value)

Then, on the button, go to the "Feedbacks" tab, and add a feedback. Select:
internal: Variable: Check value

Then select the variable you want, the properties you want to change, etc.

**Comment by PieterBoeren** [comment]
@noctividus: aren't your instructions meant for companion instead of this direct streamdeck plugin?

**Comment by noctividus** [comment]
Ah, yes...I forgot that's how I solved it. Should update solution to - "see
competition."

Sorry about that.

**Comment by cgiesche** [comment]
Related to #192. I will change this issue to make all colors configurable.
