### ISSUE TITLE
server settings wont save

### ISSUE THREAD

**Issue by mistermist8** [cgiesche/streamdeck-homeassistant#175]
whenever I install the plugin and put in the Home Assistant Server URL and Access Token it connects properly and lets me see my entities. However when I hit save at the bottom, it does not save. It simply does nothing. Then when I go back to the button, all the settings are gone.
Help please!

**Comment by jdubbs4051** [comment]
Also seeing the same behavior.

**Comment by Hessenpower01** [comment]
Which OS and SW Version are you using?

**Comment by jdubbs4051** [comment]
Sorry, that would help. Streamdeck version is 6.3.1 (18954) and os is 13.5.1 (22G90)

**Comment by cgiesche** [comment]
@mistermist8 are you using macOS, too?

**Comment by jdubbs4051** [comment]
yes, Ventura 13.5.1 (22G90). I also tried on a windows 11 PC and the plugin wouldn't install from streamdeck marketplace. Other plugins install fine.

**Comment by cgiesche** [comment]
I just completely removed StreamDeck and deleted all related folders and registry keys. After reinstalling StreamDeck, downloading the plugin from the marketplace and entering valid URL and Token, it works as expected. :/

Unfortunately i have no mac to try this.
