### ISSUE TITLE
Feature Request: Change Profiles of Streamdeck based 

### ISSUE THREAD

**Issue by Gus1994** [cgiesche/streamdeck-homeassistant#176]
Hello,
Thanks for such a great plugin ! 
Is it possible to change streamdeck profiles based on the status of a home assistant entity.
For example, my phone is "off_hook" i can jump directly to the profile related to phone control

**Comment by cgiesche** [comment]
Hi,

 

unfortunately,  it is not possible for a plugin to change anything outside its scope. So, I can “see” all buttons that are running my plugin, but I cannot access other plugins or global features of the stream-deck.

 

The existing paging or profile-switch plugins are created by elgato and seem to have special privileges to do what they do.

 

☹

 

Von: Gus1994 ***@***.***> 
Gesendet: Donnerstag, 21. September 2023 15:47
An: cgiesche/streamdeck-homeassistant ***@***.***>
Cc: Subscribed ***@***.***>
Betreff: [cgiesche/streamdeck-homeassistant] Feature Request: Change Profiles of Streamdeck based (Issue #176)

 

Hello,
Thanks for such a great plugin !
Is it possible to change streamdeck profiles based on the status of a home assistant entity.
For example, my phone is "off_hook" i can jump directly to the profile related to phone control

**Comment by Gus1994** [comment]
Ah thanks for such a fast reply ! With the power of home assistant this would be a crazy feature
