### ISSUE TITLE
Lights wont switch

### ISSUE THREAD

**Issue by Hessenpower01** [cgiesche/streamdeck-homeassistant#178]
As it seems I'm just to dumb to configure ...

Stream Deck MK2 connected to Macbook, running Streamdeck 6.3.1 with Plugin 2.3.1. Home Assistant 2023.9.3

My SD is connectzed and I can switch a plug. But how the hell am I switching lights? Tried to configure as described but I think there has been an update that changed the interface. 

Not working:

<img width="391" alt="Bildschirmfoto 2023-10-05 um 11 17 09" src="https://github.com/cgiesche/streamdeck-homeassistant/assets/57876508/7805455a-8a55-4613-9c6b-dce4ca364a67">

**Comment by cgiesche** [comment]
Can you please try the domain "light" instead of "switch" for the button settings?

**Comment by Hessenpower01** [comment]
You made my day!
Thanks for the plugin and your support
