### ISSUE TITLE
Mac install?

### ISSUE THREAD

**Issue by reffr** [cgiesche/streamdeck-homeassistant#18]
I cannot get this to install. I'm very excited to get this to work. Will this only work on a PC?  I try to add the plugin and it opens but nothing changes in the stream deck.

Thanks in advance.
Rob

**Comment by cgiesche** [comment]
The plugin should work on MacOS. Maybe this helps (another MacOs user with initial problems, but got it working):

https://www.reddit.com/r/homeassistant/comments/laq2g4/homeassistant_streamdeck_plugin_dynamic_not_just/glsd78v?utm_source=share&utm_medium=web2x&context=3

I hope this will help you.
