### ISSUE TITLE
Nabu Casa and streamdeck plugin

### ISSUE THREAD

**Issue by woldhek** [cgiesche/streamdeck-homeassistant#181]
Hi,
is it posible to use nabu casa with this plugin? If so, what should the URL be?

**Comment by cgiesche** [comment]
Hi,

i am not sure, how nabu casa works, but i found a similar question here:
https://github.com/custom-components/remote_homeassistant/issues/27

Regarding to that discussion, the URL *may* look like this (replace xxxxx of course):
wss://xxxxxxxxxx.ui.nabu.casa:443/api/websocket

Just a guess. Maybe that helps.

**Comment by tioan** [comment]
> Hi, is it posible to use nabu casa with this plugin? If so, what should the URL be?

Yes,

wss://456ds4f5s6df4sd65f4sd6few4r4we6rwer.ui.nabu.casa/api/websocket
