### ISSUE TITLE
Air Condition steering issue

### ISSUE THREAD

**Issue by palladin8282** [cgiesche/streamdeck-homeassistant#187]
Hello, 
I have an issue with AC steering from Stream Deck. 
My AC units (Daikin) are configured in HA and I can use full functionality from HA. 
From the plugin in stream deck only On/Off function seems to be working. 
I can get the readings of temp and state but I am not able to steer via plugin for functions like HVAC mode, Fan mode, Swing mode and Temp change.
I am not sure what could be an issue here, 
Is there any possibility for support ?
Many Thanks

**Comment by cgiesche** [comment]
I do not own a climate device, so i am guessing. Please note that there sould be a "entity" dropdown in your case where you select the climate entity that you want to switch:

HVAC-Mode (available values depend on your device. i think "heat", "cool" or "idle" may work)
![grafik](https://github.com/cgiesche/streamdeck-homeassistant/assets/5123180/3d641b01-a05a-4030-b119-35cb5f820722)

Swing-Mode (available values depend on your device. i found an example with value "1"...)
![grafik](https://github.com/cgiesche/streamdeck-homeassistant/assets/5123180/6371229b-7fd7-4f4e-ad33-f7cc1c8e2d51)

Target temperature (and HVAC mode), (again, available values depend on your device)
![grafik](https://github.com/cgiesche/streamdeck-homeassistant/assets/5123180/56a076d1-f5e1-4ba9-b1eb-0bb38d56c670)

**Comment by palladin8282** [comment]
Many Thanks :) I will try it and let you know, 
Great work anyways :)
