### ISSUE TITLE
Only showing status, not able to activate

### ISSUE THREAD

**Issue by Guy-Falkes** [cgiesche/streamdeck-homeassistant#196]
So I just tried to setup controlling Home Assistant entities through my stream deck and wanted to give this plugin a try.
I got it all set up and partially working.

I'm connected to home assistant, I see all my entities, so that's good.
I configure a light and an action (toggle for instance) and the button DOES show me the current status (on or off). I also see the status change when I turn the light on and off from HA. The button has a small green corner indicating it is properly connected.

What does NOT seem to work, is actually activating the light by pushing the button on the SD... I tried multiple lights, tried turn on/off instead of toggle but nothing seems to be doing the trick.

I might be doing something wrong since you all seem to have gotten it operational.
SD version: 6.4.1.19697
HA-Plugin version: 2.4.0
HA version:

- Core 2023.11.3
- Supervisor 2023.11.6
- Operating System 11.1

**Comment by xSpotix** [comment]
same problem here

**Comment by palladin8282** [comment]
Hi, 
While setting the light toggle did you select the right Entity (just below Service field) ?
Best Regards
Greg

**Comment by Guy-Falkes** [comment]
Yes, that's why i can see the correct and current status of the chosen entity on the SD. That's why I'm sure I've got the correct entity and server URL/access token because it does show the entity as a switch and display's whether it's on or off.

**Comment by cgiesche** [comment]
There are two sections: One for the display and one for the service. These are completely independent. Please make sure, you have selected the correct entity in the "keypad actions":

Keypad appearance:
![grafik](https://github.com/cgiesche/streamdeck-homeassistant/assets/5123180/ca438833-6eca-4d1d-93cd-038dcdb19694)

Keypad actions:
![grafik](https://github.com/cgiesche/streamdeck-homeassistant/assets/5123180/6deababb-4ff3-41f6-b46f-87c082e86123)

**Comment by Guy-Falkes** [comment]
I thought i had set those up correctly, but something you wrote (and one difference in your screenshots) triggered me to try something which did the trick, IT WORKS NOW...
What you said which triggered me: that these two are completely independent.
The difference in the screenshots: Your screenshot says "Entity" while my settings say "Entity (Optional)"

What works/made it work:
I added the corresponding entity in that entity field and immediately I was able to not only see the status but also change it :)

**Comment by palladin8282** [comment]
That is why I asked about filling the entity field under a service field ;)

**Comment by cgiesche** [comment]
I have removed the "optional" in the current release. You were not the only one confused about that :D

(not yet in elgato store, but you can find the current version [here](https://github.com/cgiesche/streamdeck-homeassistant/releases/download/2.4.1/de.perdoctus.streamdeck.homeassistant.streamDeckPlugin).
