### ISSUE TITLE
Why didn't you use home-assistant-js-websocket?

### ISSUE THREAD

**Issue by balloob** [cgiesche/streamdeck-homeassistant#2]
So not an issue with the code, but a question.

Home Assistant maintains [home-assistant-js-websocket](https://github.com/home-assistant/home-assistant-js-websocket/). A JS lib that is also used by the frontend and the Node-Red plugin to communicate with Home Assistant.

I see that you created your own for this plugin. Did you miss any functionality that you decided to go down this path?

**Comment by cgiesche** [comment]
It was not a real "decision", but more or less a night of coding - ignoring the possibility that something useful like this library may already exist. As this project is my first contact with javascript (as any experienced JS dev may notice), it started without use of modules - just as plain JavaScript. 

I will take a look at the lib and consider to replace my hand-made solution. I will create an issue for that. Thanks for the hint :)
