### ISSUE TITLE
Does this work on MacOS?

### ISSUE THREAD

**Issue by julianrinaldi** [cgiesche/streamdeck-homeassistant#20]
When clicking the downloaded plugin, the Stream Deck app opens, but nothing seems to be installed.

**Comment by cgiesche** [comment]
Hi. It seems like the automatic plugin installation does not work on MacOs. Until I found the reason, you can install the plugin manually like described here:

https://www.reddit.com/r/homeassistant/comments/laq2g4/homeassistant_streamdeck_plugin_dynamic_not_just/glsfayz?utm_source=share&utm_medium=web2x&context=3

Unfortunately, i do not own any MacOS device - so finding out, what goes wrong is not that easy :/

**Comment by julianrinaldi** [comment]
Got it to work. Thanks!
