### ISSUE TITLE
Automatic plugin installation seems not to work on MacOS

### ISSUE THREAD

**Issue by cgiesche** [cgiesche/streamdeck-homeassistant#21]
Workaround until this is fixed: https://www.reddit.com/r/homeassistant/comments/laq2g4/homeassistant_streamdeck_plugin_dynamic_not_just/glsfayz?utm_source=share&utm_medium=web2x&context=3

**Comment by arnonel** [comment]
Same for me

**Comment by cgiesche** [comment]
Fixed (plugin can be installed from elgato plugin store)
