### ISSUE TITLE
Actions now require (Optional) Entity

### ISSUE THREAD

**Issue by bnystrom** [cgiesche/streamdeck-homeassistant#217]
Entities such as "cover" and "switch" (and possibly others) now seem to require you to fill in the "optional" entity for either long or short press for them to work properly. Previously, the long and short action seemed to apply to the button's main entity.

**Comment by cgiesche** [comment]
Yes, that is correct. The "Optional" has been removed in the latest release.
It has not yet been published to the elgato store.but will be soon.

**Comment by cgiesche** [comment]
Fixed in latest release.
