### ISSUE TITLE
Custom title ignored on knobs?

### ISSUE THREAD

**Issue by joestump** [cgiesche/streamdeck-homeassistant#225]
I recently got a Stream Deck+ to use as a remote for HASS; thank you for this plugin! 

I'm trying to show `{{brightness}}` on the knob for my living room lights and no matter which variable I use the plugin is showing `Entity (generic)` for the title. It appears `Custom title` is ignored entirely.

### Steps to reproduce

1. Leave `Title:` empty
1. Choose `light` as domain
2. Choose a light entity that supports dimming
3. Click `Use custom title`
4. Put `{{brightness}}` in for the title value.
5. Save configuration

### Expected results

It shows the `brightness` value from HASS for the entity. In my case that should be `157` according to the HASS Developer > State dashboard. 

### Actual results

Title shows `Entity (generic)` for any custom title value. I've tried both variables and static labels; none appear to work on the knobs. 

<img width="546" alt="image" src="https://github.com/cgiesche/streamdeck-homeassistant/assets/37667/59b2016c-fb80-4063-b77a-fdd6bf246285">

It does, however, work on the buttons:

<img width="543" alt="image" src="https://github.com/cgiesche/streamdeck-homeassistant/assets/37667/9bc67a24-fc7d-49f2-b298-cf6fcde8e2f4">

**Comment by joestump** [comment]
Updating to add the variables do work on knobs in the `Custom label` field. Just not the `Use custom title` field.

**Comment by cgiesche** [comment]
Yep that seems to be a bug...

**Comment by clarinetJWD** [comment]
Has there been any movement on this? I just for a Plus, and am seeing the same issue half a year later.

**Comment by artistro08** [comment]
@clarinetJWD looks like the pre-release works really well now.
