### ISSUE TITLE
Not all HA icons are supported?

### ISSUE THREAD

**Issue by kchiem** [cgiesche/streamdeck-homeassistant#226]
It appears that only a subset of HA's icons are supported in this, eg. mdi:home-lightning-bolt doesn't work.  Is there a way to improve this?

**Comment by cgiesche** [comment]
I am using an mdi-library for this. I will check if there are any updates that contain those missing icons.

**Comment by cgiesche** [comment]
As far as I see, all material design icons should be supported by the plugin. When I change the icon of an entity to "home-lightning-bolt", it is displayed correctly:
![image](https://github.com/cgiesche/streamdeck-homeassistant/assets/5123180/7db37372-e758-4840-9198-d8d37bdcf056)

I am currently implementing a complete rework of how icons work in the plugin, so we will have to check back later and see if this problem persists.
