### ISSUE TITLE
Plugin failing to communicate

### ISSUE THREAD

**Issue by kBraDrs** [cgiesche/streamdeck-homeassistant#227]
Hello,

I have installed the plugin for home-assistant, input the url of the instance, and input the long-lived access token. But am unable to control my devices with it.

The devices in my home show up, so I know that the connection is active and working, and when I switch devices on/off in the home-assistant web app, the status on the stream deck changes, so I can see when devices are on or off with it. 

Screenshots are below of what my settings are, is this something that you know how to fix?

![image](https://github.com/cgiesche/streamdeck-homeassistant/assets/102444317/be8ad530-fde7-41f5-ac63-923184816d14)

![image](https://github.com/cgiesche/streamdeck-homeassistant/assets/102444317/82029a1a-825c-430e-8b26-ca08fe84ca4a)

![image](https://github.com/cgiesche/streamdeck-homeassistant/assets/102444317/a71801b5-b8ed-46e1-8612-68e5951bb7d3)

**Comment by kBraDrs** [comment]
For addition, I cannot see any requests for this in the homeassistant logs, and there are also no debug methods that I can find for the streamdeck plugin.

**Comment by cgiesche** [comment]
Normally, between Service and Service data, there should be a third drop-down where you can select the entity you want to turn on.
If it is not visible, this normally means, that there isn't any light entity that supports the turn-on service. Maybe you have to use the "switch" domain instead of "light"?

**Comment by kBraDrs** [comment]
I see, I can confirm that none of the domains allow me to choose an entity for this. I will have a play around in HomeAssistant to see if anything needs to be changed there, if you have any ideas, please let me know. 😊

**Comment by kBraDrs** [comment]
I have wathced other videos on how to do this and they do not have what you are saying, but do have the below, which is a screenshot from my machine so to confirm that I can see this and have set this correctly.

![image](https://github.com/cgiesche/streamdeck-homeassistant/assets/102444317/25352646-5288-4590-b5b1-bfff31012bae)

Also, to rule out any other affecting factors, I have re installed Home Assistant to try and get this working so this is the only entity linked to it.

**Comment by kramttocs** [comment]
If you got to Developer > Services in HA and use the light.turn on service. Does your entity show up and respond?

**Comment by kBraDrs** [comment]
Yes I have just done this and it turned the light.turn_on service worked and vice versa

**Comment by joestump** [comment]
@kBraDrs I had this happen to me as well. Are you on 2.4.2? Try rolling back to 2.4.1 and disabling auto updates. I had the same issue as you it sounds like: https://github.com/cgiesche/streamdeck-homeassistant/issues/193#issuecomment-1868189281

**Comment by kBraDrs** [comment]
> @kBraDrs I had this happen to me as well. Are you on 2.4.2? Try rolling back to 2.4.1 and disabling auto updates. I had the same issue as you it sounds like: [#193 (comment)](https://github.com/cgiesche/streamdeck-homeassistant/issues/193#issuecomment-1868189281)

That was it! It's working perfectly. I have quite a complex networking system at home and spent all of yesterday tracking down whether my network was blocking internal websocket requests 😂 Glad to find out it was this simple all along.

Thank you @joestump, you have made my morning 😊

@cgiesche Any idea why the newer version is not working correctly?

**Comment by cgiesche** [comment]
Oh ****.

It's my friend Jesus birthday today and I am far away from my computer for some time. 

I have no idea what is going on but I will try to get the store version rolled back to the last working version. This may take some time...

You may download and install the "latest" version from releases page (coming in some minutes). This can be installed manually and you do not have to disable automatic update from store.

**Comment by joestump** [comment]
@kBraDrs I have a similarly complex network with multiple VLANs and was worried that was an issue, but all of the devices were on the same VLAN. Interesting that there's overlap in our setup; wonder if there's something (bad network dependency update?) in 2.4.2 causing issues with VLAN tagging?

**Comment by cgiesche** [comment]
I am not at home, so I can not really check what it is, but it seems to be a general bug and not related to your network setups.

**Comment by joestump** [comment]
Not sure if others are dealing with this, but even with "Automatically update" unchecked the plugin is auto-updating nightlight, which breaks things all over again. Presumably the Stream Deck software itself has a bug that ignores disabled auto-updates. 😢 

Is it possible to pull the 2.4.2 release?

**Comment by cgiesche** [comment]
Hello everyone. 

I just got home and immediately tried to reproduce the issue. I completely uninstalled the plugin and installed the current version (2.4.2) from the Elgato Store. "Unfortunately," everything seems to be working as expected on my end:

![image](https://github.com/cgiesche/streamdeck-homeassistant/assets/5123180/d427f518-563d-46fa-97ba-a4a755288b7a)
![image](https://github.com/cgiesche/streamdeck-homeassistant/assets/5123180/a3dd63ee-937c-4be0-bc94-b54911d36650)

Does this issue occur with existing buttons (those that existed before the update) or with newly configured ones as well?

**Comment by joestump** [comment]
I started an entirely new profile with new buttons and nothing worked. It also persisted across two computers as new profiles with new buttons failed to address the issue. Both macOS and Windows 11.

**Comment by MooseTheory** [comment]
I believe I am experiencing this issue as well.
I just installed today (1 January 2024). I originally installed from the Elgato Marketplace and received version 2.4.2. After I was unable to get that to function, I did some googling, and stumbled across this. Downgrading to the 2.4.1 build from github did not alleviate my issue though.
The biggest difference I can think of between my config and others is that I am using the remote domain.

**Comment by MooseTheory** [comment]
> I believe I am experiencing this issue as well. I just installed today (1 January 2024). I originally installed from the Elgato Marketplace and received version 2.4.2. After I was unable to get that to function, I did some googling, and stumbled across this. Downgrading to the 2.4.1 build from github did not alleviate my issue though. The biggest difference I can think of between my config and others is that I am using the remote domain. I have also tried uninstalling and purging everything I could find from the Stream Deck software and reinstalled, only using the 2.4.1 build, but I am seeing the same behavior.

So, after being stumped by this yesterday, suddenly, today it has the Entity... I am confused, but it works for me now on 2.4.1.

**Comment by forcepd** [comment]
Wanted to share I am seeing the same issue on a new install on 2.4.2 from the Marketplace. The status on the icon appears to be syncing correctly (e.g. when I turn the light on/off the change shows on the button). But I can't get the short press or long press to work and both are missing the "Entity" dropdown after I select the Domain and Service dropdowns although the "Service Data JSON (optional) section appears. 

Glad to do any troubleshooting for you if helpful.

**Comment by cgiesche** [comment]
I'm slowly going crazy:

- I uninstalled the Stream Deck application on my main PC and deleted all directories (caches, settings, plugins), then reinstalled it completely: The plugin works.
- I installed Stream Deck from scratch on my notebook: The plugin works.
- I've tried it on both using both the XXL and SD+.
- I've tried both admin and regular user tokens from Home Assistant.

I don't understand it.

Maybe someone who is experiencing the issue (on Windows) can check if there is an error in the debug console. Here's how to do it:

- In the Registry, navigate to `HKEY_CURRENT_USER\Software\Elgato Systems GmbH\StreamDeck` and set the key `html_remote_debugging_enabled` to the value `1` (DWORD).
- Restart the Stream Deck application.
- Go to a button configuration with the Home Assistant plugin on the Stream Deck (stay on this page!).
- In your web browser, navigate to the page [http://localhost:23654/](http://localhost:23654/).
- Click on "HomeAssistant Plugin PI" (important: PI).
![image](https://github.com/cgiesche/streamdeck-homeassistant/assets/5123180/39216988-6388-41de-af39-6159c951b194)
- Switch to the "Console" view and then try to configure an action on the Stream Deck (do not leave the "button" page).
Ideally, you should see an error in the console if there is an issue.
![image](https://github.com/cgiesche/streamdeck-homeassistant/assets/5123180/e7a3f0d5-af0b-4b5f-8c17-796b4855c449)

**Comment by forcepd** [comment]
Here is the screenshot I have after following those steps:

![Screenshot 2024-01-03 155829](https://github.com/cgiesche/streamdeck-homeassistant/assets/76794217/22b09416-5e6f-4ec1-84c1-d4503fa8853c)

**Comment by forcepd** [comment]
Also not sure if this matters but I'm running on Windows 10

**Comment by cgiesche** [comment]
> Here is the screenshot I have after following those steps:

Thank you! Nothing unusual to see there :/

> Also not sure if this matters but I'm running on Windows 10

In this case, it does not matter. My personal verdict is, that there must be at least one "special" entity in your home-assistant, that somehow causes the problem. 

Maybe, you or someone else with this issue can make this request and share the response with me:
https://reqbin.com/c-2qwz2ahd

**DISCLAIMER** The respone contains the names, ids and current state of **ALL** our home assistant entities. If you do not want to share this data with the public, please attach the output to a mail and send it to me ([christoph.giesche_github@cgidev.de](mailto:christoph.giesche_github@cgidev.de)). I will only use it to find out, if one of the enties is causing the problem and then delete this data.

- Replace "TOKEN" with a fresh token from Home-Assistant (delete it afterwards).
- Replace the first part of the URL with your Home-Assistant hostname and port
- Click "Run"
![image](https://github.com/cgiesche/streamdeck-homeassistant/assets/5123180/79bfc9c3-00f5-4994-b3d3-fd8c5ee690fd)

After your request succeeded, it should look like this:
- Status should be 200
- The content in the text box (depending on your entity count it may be huge) is, what i need.
![image](https://github.com/cgiesche/streamdeck-homeassistant/assets/5123180/f01767d2-3c51-457f-82fd-97e9fae5e4bd)

**Comment by forcepd** [comment]
Thanks. I will take a look at this later tonight and email you the output.

Note that the first time I select the entity box under keypad appearance, it appears to work correctly; i.e. I select "light" from the dropdown under Domain and then all of the lights are populated correctly under the Entity dropdown list.

**Comment by codeandcats** [comment]
Any updates on this? I am experiencing the same issue:

OS: MacOS 14.2.1
Stream Deck: 6.4.1 (19697)
Home Assistant Plugin: 2.4.2 (from Marketplace)

I'm happy to help out anyway I can with sending diagnostics but am unsure how to do so on Mac.

**Comment by cgiesche** [comment]
> Interestingly, the plugin doesn't even seem to make requests for services where the entity is specified in the service data. Case in point, the following works perfectly in HA

Everything points to the problem being one or more entities that somehow break my code. Yesterday I installed my PC from scratch, did not use any backups and the plugin is working perfectly fine.

You can help like described above:
https://github.com/cgiesche/streamdeck-homeassistant/issues/227#issuecomment-1877768549

With this data, I could import your entities in my local plugin (of course, i can not control them or view live data as this is only a snapshot) and hopefully, the error will occur.

**Comment by codeandcats** [comment]
@cgiesche I have a large network of devices which I'm not comfortable sharing, even with someone privately, I hope you can understand.

I do agree though that this is environmental.

May I suggest another way to approach this? If it were true that there is some sort of entity was causing the code not to show the list of entities, and prevent requests from sending, what are the most likely places of code that would be error?

I'm unfamiliar with the codebase, Vue and Stream Deck plugins, but if I were to take a high probability stab in the dark... I wonder if the code is expecting a property to exist on an entity and it's accessing a sub-property/method of it but the property is `undefined` for a particular entity.

Some suggestions:
- Focusing on the area that is likely to contain the problem, double-checking how and which properties are accessed and whether they can be accessed in a safer way (e.g. using [optional chaining](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining))

- Adding some error catching and logging to the likely area or adding UI elements in a special "debug" release which give feedback on any errors, etc

**Comment by cgiesche** [comment]
I have just created a debug release which has to be installed manually (https://github.com/cgiesche/streamdeck-homeassistant/releases/tag/2.4.3).
It does perform intense logging at the place where available entities are filtered after selecting a service for a service.

You can access the logs like described in https://github.com/cgiesche/streamdeck-homeassistant/issues/227#issuecomment-1875988101.

Example output:
![image](https://github.com/cgiesche/streamdeck-homeassistant/assets/5123180/9fc5f3cb-783b-4c8c-889e-7e81d3a258df)

**Comment by codeandcats** [comment]
@cgiesche Here is a screenshot of the JS console along. Note that I tweaked your build slightly to just output the count of available entities and services rather than outputting the entities and services themselves.

<img width="770" alt="Screenshot 2024-01-27 at 2 17 55 pm" src="https://github.com/cgiesche/streamdeck-homeassistant/assets/6035934/d32bb0ac-eb6e-4de1-828f-61c536c3b36d">

I hope this is helpful. I also privately emailed you a screen-recording of my session if that's more helpful.

**Comment by cgiesche** [comment]
I've also just come to the same realization. Thanks for the support!

And once again, as a Java developer, I've fallen victim to the type uncertainty of JavaScript. :D

**Comment by cgiesche** [comment]
Here we go: https://github.com/cgiesche/streamdeck-homeassistant/releases/tag/2.4.4

This will hopefully be the next release for the elgato store. Besides (hopefully) fixing this issue, It contains some other minor fixes and improvements.

Please feel free to test and give your feedback.

**Comment by codeandcats** [comment]
> And once again, as a Java developer, I've fallen victim to the type uncertainty of JavaScript. :D

Haha, well you're in good company. As a former C# (basically Java) dev myself, my advice is to embrace TypeScript! 😅

`2.4.4` seems to be working as expected 👌
Thanks for your time, patience and persistence 💯 🥇
