### ISSUE TITLE
Logging when connection isnt available

### ISSUE THREAD

**Issue by rw377** [cgiesche/streamdeck-homeassistant#23]
When setting this up, I am putting in my HA URL per the example alongside my access token, but the app is not showing me domain, entities, etc. I assume the connection isn't being made but I can't tell. Is there any way to diagnose this further through logging in either Stream Deck or HA?

**Comment by cgiesche** [comment]
There is a built in debugging mode for the StreamDeck app:
https://developer.elgato.com/documentation/stream-deck/sdk/create-your-own-plugin/

After enabling it, you can open http://localhost:23654/ in Chrome and select one of the two "parts" of the plugin:
![image](https://user-images.githubusercontent.com/5123180/111530813-0d076580-8764-11eb-9444-2445523cd4a3.png)

"PI" is the debugger for the configuration page and is only available once you selected an item in the stream deck app. The other is for the plugin itself. Debugging works like debugging a "normal" web page in Chrome.

**Comment by rw377** [comment]
Thank you @cgiesche, this helped solve my issue.
