### ISSUE TITLE
Custom icon entities ignore actual state when pressed

### ISSUE THREAD

**Issue by Guspaz** [cgiesche/streamdeck-homeassistant#234]
If you create a button of type "Entity (custom icons)", then pressing the button toggles between on and off regardless of the actual state of the entity. For example, if the appearance entity is a switch, if you set the action to "turn on", you would expect repeated presses to leave the visual state always on, but instead the visual state toggles back and forth. Or if you set an action that does not affect the switch state (or does not affect it immediately), you would expect the visual state to remain unchanged, but instead it toggles on and off.

This does not happen with switches created from "Entity (generic)", those correctly reflect the entity state. This only affects custom icon entities. The visual state does correctly update on its own if the state changes in HASS, the problem only seems to be that the state changes on button presses instead of waiting for HASS to say the state has changed.

This bug occurs regardless of what type of entities are used, pressing the physical button always toggles the visual appearance between on and off even if the appearance entity has a binary state that differs from this.

**Comment by Guspaz** [comment]
Looking at the Stream Deck SDK, it looks like it's the Stream Deck that will automatically toggle between states when the key is released. A workaround to this may be for the plugin to call setState every time it receives a key release event, to update the state to the HASS state.

**Comment by Guspaz** [comment]
Can confirm, setting "DisableAutomaticStates" to true in the plugin's manifest.json file fixes this bug completely. This solution only works for two-state actions, but that's what this plugin uses, so it's perfect.

**Comment by cgiesche** [comment]
Hi @Guspaz,

that is a nice finding! From the beginning the automatic switch behaviour was a problem.
I am quite sure i did not find anything like "DisableAutomaticStates" that when i initially added the feature. Maybe the option has been added to the API meanwhile

I will add this to the manifest.

**Comment by Guspaz** [comment]
You can find the documentation for it here: https://docs.elgato.com/sdk/plugins/manifest#actions
It was added in 6.4: https://docs.elgato.com/sdk/plugins/changelog
So it's probably very recent. It's also bizarre that it only works on actions with two states, and not three or more, but since this plugin only has either one or two states, that isn't a problem.

**Comment by sammyke007** [comment]
I'm facing this too. I have an icon setup for my front door state (binary door/window sensor). On key press it opens the door lock (sensor.***). When I click the butto, the doorlock opens, but the door is still closed. The icon changes to the open state however. Is this the fix?
