### ISSUE TITLE
Plugin Starts Disconnected

### ISSUE THREAD

**Issue by Maxcodesthings** [cgiesche/streamdeck-homeassistant#247]
When my computer boots the plugin does not connect to my instance. I have to force quit and start Stream Deck every time.
Is there a way to debug this or send logs?

**Comment by therysin** [comment]
Same happens to me, except when waking from sleep mode. Boots and loads fine.

**Comment by Brandon1212b** [comment]
Same issue just happened to me.
1. computer went into sleep mode (which turn deck off)
2. I turned my computer back on
3. Deck is back on but when I click any home assistant button I get the yellow caution sign error

Only fix was force closing Stream Deck and reopening

**Comment by Brandon1212b** [comment]
Confirming that this issue happens every time my computer returns from sleep mode

**Comment by Maxcodesthings** [comment]
I have done more digging on this in the community. I think its not an issue with this plugin but one with Stream Deck itself. Other plugins tend to fail as well on boot or resuming from Standby.

The best workaround I found for the solution is to create a script to reboot Stream Deck. This is the post that helped me, i hope it can help others: https://www.reddit.com/r/elgato/comments/yx9g5m/stream_deck_is_often_unresponsive_on_wake_from/

**Comment by therysin** [comment]
Created a task to automate rebooting the process when waking from sleep:

https://www.reddit.com/r/elgato/s/QuGNQbeEXL
