### ISSUE TITLE
Update not in Elgato Store

### ISSUE THREAD

**Issue by dpeet** [cgiesche/streamdeck-homeassistant#253]
Hey @cgiesche!

Thanks for this great plugin.  I was having some minor issues with buttons not actually doing anything, and in the course of troubleshooting realized that the latest in the store is 2.4.2, not the 2.4.5 you released a couple weeks ago.  I was able to fix my issue by restarting the stream deck app, but thought you ought to know the update hadn't made it through!

**Comment by cgiesche** [comment]
I have asked elgato to publish the release. I will close this issue after it is done.

**Comment by cgiesche** [comment]
The update has now been released by elgato.
