### ISSUE TITLE
server settings do not save

### ISSUE THREAD

**Issue by domx4q** [cgiesche/streamdeck-homeassistant#258]
Hello, today I wanted to use this plugin to manage my smart home system.
My problem is that I can't get it set up. Once I enter the server URL and the access token, I can connect and make the settings. But as soon as I press another field and then go back to the corresponding button, the plugin has forgotten the login data. If I then log in again, the previous configurations are still available. However, I cannot use the button as it immediately forgets the settings again.
And yes, I have pressed Save (several times).

I am using the latest version of the plugin (2.4.5). I am running on Windows 11 (build number: 10.0.22631 build 22631). I am using the latest version of Stream Deck (6.5.2 (19936)). I connect to Home-Assistant via https.

**Comment by domx4q** [comment]
Suddenly it works.

**Comment by cgiesche** [comment]
Hmm, that's good because I had no.idea what may have caused that issue :D

**Comment by shoot991** [comment]
Same issue
