### ISSUE TITLE
3.5.0 Bug: The new encoder interface doesn't account for light templates 

### ISSUE THREAD

**Issue by artistro08** [cgiesche/streamdeck-homeassistant#286]
More specifically, it doesn't account for light templates that have brightness. I was able to fix it with removing the extra check to see if an entity supports brightness, but I'm sure it's more to it than that. 

The code in question is in this pull request: https://github.com/cgiesche/streamdeck-homeassistant/pull/278/commits/7045251e1b48c2823b4d1eba75f8d3c01a24afba#diff-f3a791ff83a40638fd40e4bbbaaed1736d898d54b967e775133d292bfd5e1b8e on line 90

**Comment by cgiesche** [comment]
This may have been fixed with the newest version.

**Comment by artistro08** [comment]
It is, but just a heads up, the speakers don't have the volume sliders anymore. it uses a custom display. By speakers, I mean `media_player`
