### ISSUE TITLE
Plugin 3.5.1 reports as 3.5.2 in StreamDeck App

### ISSUE THREAD

**Issue by Nealtron** [cgiesche/streamdeck-homeassistant#294]
Manually downloaded and installed 3.5.1 using [this link](https://github.com/cgiesche/streamdeck-homeassistant/releases/download/3.5.1/de.perdoctus.streamdeck.homeassistant.streamDeckPlugin) located in the 3.5.1 release announcement, and within the StreamDeck App it is reporting the plugin as version "3.5.2".

![image](https://github.com/user-attachments/assets/42c09f56-4b28-4d65-80d8-06a1cdc677ab)

**Comment by cgiesche** [comment]
Hi,

that ist ok. 3.5.1 contained a bug and to avoid that users destroy their config, I replaced the release with a bug fixed version (3.5.2).
