### ISSUE TITLE
Binary Lights don't show up correctly and fall back to showing the HA logo.

### ISSUE THREAD

**Issue by NBSgamesAT** [cgiesche/streamdeck-homeassistant#295]
# Description
Making a generic entity button on Streamdeck and set it's entity to a binary light will cause it to show up with the HA logo and a warning triangle instead of as any other switch.

**Effected Version: 3.5.2 (As of per Streamdecks Software) 3.5.1 (As per Github releases)**

# Steps to reproduce 
- Create a new generic entity button on the stream deck
- Set the Entity to a binary light source

# Expected Behaviour
The button switches from the generic HA logo to a switch icon and shows the state of the light

# Actual Behaviour
The buttons stays as the generic HA buttons and even shows the warning triangle when you attempt to press it.

# Other nodes:
The press and long press actions do not seem to be effected in any way.

I have also posted a picture of the esphome config of the light causing this issues and a picture of what it shows up as on the Streamdeck

<img width="154" alt="ESP home config of the light" src="https://github.com/user-attachments/assets/b911f918-524f-4c49-ac34-0e70b7b3c515">

<img alt="What it shows up on the SD" src="https://github.com/user-attachments/assets/13e95658-8db3-4419-992b-5217238c185e" width="58">

**Comment by tomazbc** [comment]
Same issue, after the update one of two icons I have defaults to the HA logo.
Since it auto updated took me a while to figure out that that update broke it.

Funny thing is, they both control the same type of device, light, just one refuses to show the changing light status icon.

**Comment by cgiesche** [comment]
Thank you for you reports!

Can you tell me what kind of entity this "binary ligth source" is? Is it a "binary_sensor" with device_class "light"?

**Comment by cgiesche** [comment]
> Funny thing is, they both control the same type of device, light, just one refuses to show the changing light status icon.
Is there a difference between those lights? Maybe one of them has color support and the other is simple on/of?

**Comment by NBSgamesAT** [comment]
The developer tools in HA. right. I've forgotten that those existed as I might the light.

> Can you tell me what kind of entity this "binary light source" is? Is it a "binary_sensor" with device_class "light"? I have both normal "light" entities and "switch" entities, as well as some binary_sensors that work as expected.

With binary light I meant a light that is truly just on/off. No colour support, no dimming, no nothing.
I have a few lights that do have full rgb color support and can also dim, that light works as expected, and even shows with a light bulb icon. 

Here is the HA Developer Tools from one of the lights that don't work correctly:
<img width="820" alt="Light that doesn't work" src="https://github.com/user-attachments/assets/e7019f57-2bf1-40f6-875c-985436992b28">

Here's an other one:
<img width="819" alt="Light that also doesn't work." src="https://github.com/user-attachments/assets/f26760df-e86f-442e-bc35-4067540b0277">

And for completeness: This one ***does*** work:
<img width="734" alt="This one works, possibly because of the rgb color support, possibly because of some of the other infos in there" src="https://github.com/user-attachments/assets/4fa81346-f526-4780-ac6f-a0c6a1f961bd">

**Comment by cgiesche** [comment]
Ok, i found out, what may be the problem:

For encoders on StreamDeck+ i user the brightness-attribute. This is not present on your light entities and causes the problem. I will try to fix this asap.

Maybe you can verify this by adding "brightness: null" to one of your non-working entities and press "set state". This should make it working (at least until home-assistant updates the state and removes that attribute again).

**Comment by cgiesche** [comment]
I fixed the issue. Luckily i was able to fix this in the configuration that is automatically updated in the plugin. Unfortunately, the stream deck seems to cache this config. So it may get this updated version in 7 days from now :/

**Comment by NBSgamesAT** [comment]
Thanks mate, I can confirm, you fixed it.

I was able to set the display configuration back to stable afterwards and it continues working.
