### ISSUE TITLE
Group Toggle?

### ISSUE THREAD

**Issue by mrwulff** [cgiesche/streamdeck-homeassistant#33]
Is it possible to toggle a group of switches?

It looks like a group is not what i think it is?

https://prnt.sc/11f6p8z

**Comment by cgiesche** [comment]
Hmm, it looks more like services for a user group to me?

Technically, i am just asking home-assistant "what services are available for entities of the domain type 'group'" and it returns the list, you can see in your screenshot.

I will create an entity group in my home assistant to see what happens.

**Comment by cgiesche** [comment]
This might be fixed with #35 .

**Comment by cgiesche** [comment]
No, will not be fixed with #35. Toggling a light group should work, if it is really configured as a "light group".
