### ISSUE TITLE
Suggest: add second service for long press button.

### ISSUE THREAD

**Issue by cnstudio** [cgiesche/streamdeck-homeassistant#34]
Is it possible to add second service for "long press" the button?
original service for "short press", this will double the button function?

**Comment by cgiesche** [comment]
Great idea and not too hard to implement, i think.
I will check this out :)

**Comment by cgiesche** [comment]
"Long press"-Service is included in Release 1.3.0 (https://github.com/cgiesche/streamdeck-homeassistant/releases/tag/1.3.0)

**Comment by cnstudio** [comment]
Tested, and works like a charm~~   :)
