### ISSUE TITLE
Cannot Save Setting

### ISSUE THREAD

**Issue by beerygaz** [cgiesche/streamdeck-homeassistant#38]
I have tried entering the wbsocket address as 
wss://<ip>:<socket>/api/websiocket per the readme.  I've also tried ws:// (per the example)

I cannot get the "exclamation" icon to go "green"

The same goes for entering my long-term-access token.

Can enter is manually to avoid the validation process?

**Comment by dsjames** [comment]
Same issue, running on macOS... Tried latest version (1.3) and version before, no dice.

**Comment by cgiesche** [comment]
Did you have a previous version of the plugin installed, or are you starting from a fresh install? Are you using windows or mac?

I will try to remove my configuration completely to check out, if this happens to me, too.

The validation is simple as "this field must contain at least 5 characters", so it should switch to "green" even if you entered "xxxxxxx".

**Comment by beerygaz** [comment]
First install. Using a Mac. Tried 6 x’s and no luck.  Will try previous version and report back.

**Comment by mikeeuk1** [comment]
Hello - tried myself - new install - Windows - same issue  - can not save settings.

![image](https://user-images.githubusercontent.com/80429366/116934792-53a21800-ac5d-11eb-80d6-b22581fbf584.png)

**Comment by cgiesche** [comment]
Oops.

**Comment by mikeeuk1** [comment]
Older version does work :-)  thanks for the hint - using 1.2.0 for now 👍

**Comment by cgiesche** [comment]
Installing and configuring 1.2.0 and then upgrading to 1.3.0 _might_ work. I marked 1.3.0 release as broken and will fix it.

**Comment by mikeeuk1** [comment]
okay will try upgrade and let you know

**Comment by mikeeuk1** [comment]
Okay - quick response - but that worked fine :-)

**Comment by cgiesche** [comment]
Ok, i fixed the bug, but now the release process broke for unknown reasons. Please stand by...

**Comment by cgiesche** [comment]
https://github.com/cgiesche/streamdeck-homeassistant/releases/tag/1.3.1
