### ISSUE TITLE
How to turn on two lights at the same time

### ISSUE THREAD

**Issue by rayjlinden** [cgiesche/streamdeck-homeassistant#42]
I have a couple Elgato Key Light Airs.  The stupid Elgato Command Center keeps getting disconnected from the key lights.  However, HA has no problem turning the lights on and off!

So I want to turn the lights on with this plugin on StreamDeck.  Was really simple to have it control one light.  Worked like a charm!!!

However, I want it to turn both my lights on at the same time.  Not sure how to do that.  I'm thinking some level of JSON code in the entity payload will do the trick.  But where can I find more info on what that should look like?

**Comment by rayjlinden** [comment]
I tried this but it does not work:
```
{"service": "light.toggle", "target": {"entity_id": ["light.elgato_key_light_air_2", "light.elgato_key_light_air"]}}
```

**Comment by cgiesche** [comment]
Hi,

you can switch multiple entities (currently limited to entities of the same domain (for exampe "light")) by manually editing the service data:

```
{
  "entity_id": [
    "light.lowboard_wohnzimmer",
    "light.elgato_key_light_7378"
  ]
}
```

![image](https://user-images.githubusercontent.com/5123180/122525700-c9015680-d019-11eb-970e-7314e81faba2.png)

**Comment by rayjlinden** [comment]
I got close!  Thank you!  That does the trick!
