### ISSUE TITLE
Leave Feedback for Release 1.4.0 here 👋 

### ISSUE THREAD

**Issue by cgiesche** [cgiesche/streamdeck-homeassistant#45]

**Comment by soleous** [comment]
Just started to play with this and I think I can get some great use out of it.  So thank you very much, it needs adding to their official plugs.

My constructive feedback would be, to instead of opening a "Home Assistant Settings" window would be to have a button to open it or integrate the settings.  After initial configuration, I'll only want to move them around, so when I have many, it will get annoying and feel disconnected from Stream Deck and other plugins.

Again thanks and great work.

**Comment by cgiesche** [comment]
Thank you very much for your feedback!

> My constructive feedback would be, to instead of opening a "Home Assistant Settings" window would be to have a button to open it or integrate the settings. After initial configuration, I'll only want to move them around, so when I have many, it will get annoying and feel disconnected from Stream Deck and other plugins.

Yeah, i can fully understand your point. Yesterday, i reorganized my buttons and got annoyed, too :D

I will try to find a suitable solution.

**Comment by Leolele99** [comment]
Version overall works very well, much more snappy than other solutions or workarounds I used.
I agree with soleous about the window button.

Though I wanted to ask,Is iteration over values, like brightness, possible?
I know you can specify certain brightness percentages or values to be set when pressing the button, but can you do a button that increases the brightness by 10 percent everytime its pressed?

**Comment by cgiesche** [comment]
@Leolele99 You can create services in home assistant that do the "heavy lifting" of increasing light xy by 10% and then call the service from my plugin (for example short press brighter, long press darker):

Example in Home-Assistant (failed to switch to english UI):
![image](https://user-images.githubusercontent.com/5123180/125123530-117ed200-e0f7-11eb-9430-e9686b39cdee.png)

yaml-version of above config:
```
alias: Increase Brightness Service
sequence:
  - type: brightness_increase
    device_id: e8ac2507c0805a0e0fad14d30aee8e30
    entity_id: light.elgato_key_light_7378
    domain: light
mode: single
```

Usage in plugin:
![image](https://user-images.githubusercontent.com/5123180/125123530-117ed200-e0f7-11eb-9430-e9686b39cdee.png)![image](https://user-images.githubusercontent.com/5123180/125123465-fd3ad500-e0f6-11eb-858d-2df8f6b4f5da.png)

**Comment by gtrabanco** [comment]
<img width="474" alt="Screenshot 2021-07-16 at 16 50 21" src="https://user-images.githubusercontent.com/1969593/125966668-d20e3a08-a50f-41b1-a2aa-9e2468b6c82d.png">

I increase by 20
