### ISSUE TITLE
Custom Images?

### ISSUE THREAD

**Issue by avviano** [cgiesche/streamdeck-homeassistant#46]
First off, great app. Congrats and thanks so much for sharing here! 

I have been using IFTTT so far to integrate to my smart home devices. I have spend many hours and days creating beautiful custom on / off icons. I would like to use them, how can I do that in your app? I can set one icon it seems, but no toggle icon. I have even created some animated gif which I use for countdowns and so on. Worked great in the IFTTT integration. Seems like I can only use one icon with your integration? Any plans to let us create custom toggle buttons?

Quite honestly, I get were you are coming form with your dynamically created icons. But believe me, it wont work. Most of the time the label text is not even fully visible. I have tried it so many times before myself. It will only be nice if you create custom icons (after all, we set them up once and that is it). 

Anyway, thanks again for your hard work. I think I can say that we all appreciate it very much. 

Cheers,
Walter

**Comment by ibmlmjm** [comment]
same here. Would love to be able to have custom toggle icons. 

Thanx!

Michael

**Comment by cgiesche** [comment]
Thanks for your feedback :). For entities with "on/off"-states, it will be possible to define custom icons after i fixed #7  (duplicate).

**Comment by avviano** [comment]
Ok great. Custom icon will make the app 100% more awesome. Cheers!

**Comment by ibmlmjm** [comment]
Yes customs icons will be greatly appreciated. Thank You! Michael
