### ISSUE TITLE
Green Circle in the top right?

### ISSUE THREAD

**Issue by abrondijk** [cgiesche/streamdeck-homeassistant#48]
As soon as I choose a service for the light that I have selected, what seems like part of a green circle appears in the top right corner of the icon on the stream deck. Why is this?
![Clipboard01](https://user-images.githubusercontent.com/73667900/126871025-914ca253-9b9e-4f29-95ac-5f4f471f85f4.jpg)

**Comment by fmarkf** [comment]
Tiny makers at the top right corner of each button image:

No marker: Button is display only and has no service assigned
Green marker: Button has a normal (short-press) service assigned
Blue marker: Button has a long-press service assigned

**Comment by cgiesche** [comment]
@fmarkf Thanks for answering the question :)

I can understand if someone does not like the circle. I am planning to allow to disable it or customize it's color. Currently i am under heavy work load, so things go a little slow.

**Comment by cgiesche** [comment]
Toggle for this indicator will be added to next release.
