### ISSUE TITLE
Trying to use this on LegatoLegacy

### ISSUE THREAD

**Issue by Bodge-IT** [cgiesche/streamdeck-homeassistant#49]
Hi, thanks for the work on the plugin.
Just wanted to check with you on whether this should be compatible with the legacy version of StreamDeck that has been modified to work on Win7/8 etc?
I know this is a very small use case but there are still some who use win7 and doesn't seem like it would take a lot of work to make it work?

https://github.com/atom0s/ElgatoLegacy

I've tried it but settings for the plugin just has Title, nothing else.

**Comment by cgiesche** [comment]
Hi,

this may have to do with the way settings (currently) work in my plugin. They are opened in a new window - it sounds like this step does not work with ElgatoLegacy.
Maybe this will change in one of the next releases, but only if configuration fits into the (unnecessarily) tiny box that the streamdeck UI provides.

**Comment by gtrabanco** [comment]
Do not know if that possible but you can do a paging of the configuration options and show only the first page (server and token configuration) first by default if no value is defined.

Additional configuration (long press) could keep in the next configuration "page" or tab or whatever but I do not know if that is possible in streamdeck... The code that is showed is regular html?

**Comment by cgiesche** [comment]
I will change the settings from popup window to the "internal" mini-window. This may fix this problem.
https://github.com/cgiesche/streamdeck-homeassistant/issues/52

**Comment by Bodge-IT** [comment]
@cgiesche I tried the latest s-h on latest ElgatoLegacy with the new config interface and it still doesn't show up.
Thanks for looking and considering a potential fix.
