### ISSUE TITLE
sensor and action?

### ISSUE THREAD

**Issue by Mikeput** [cgiesche/streamdeck-homeassistant#50]
Is it possible to have a sensor displayed and when pressed preform an action?

e.g. room temperature and when pressing that button on the stream deck toggle a fan?

**Comment by dennisbrouwer91** [comment]
Yes that is possible

**Comment by cgiesche** [comment]
Ok, I thougt that was not possible because you can only select a single entity (sensor OR switch) for both display and action. Maybe you can create a "virtual" entity in home assistant that allowes this?

**Comment by Mikeput** [comment]
how is it possible when you create a double entry it has a 3 blue diamonds have an icon in streamdeck?

@dennisbrouwer91 care to elaborate how you can do this in HA?

**Comment by markgravo** [comment]
Is there an example of how to actually do this? I can do one or the other but not both.
