### ISSUE TITLE
Suggestion: activate scenes

### ISSUE THREAD

**Issue by sanderdatema** [cgiesche/streamdeck-homeassistant#51]
I would love to be able to activate a scene with a button. So, here's my feature request. 😀

**Comment by cgiesche** [comment]
You can already activate a scene by selecting "scene" in the domain dropdown:
![image](https://user-images.githubusercontent.com/5123180/130406122-34f31580-fe22-413d-b653-ac48eee8b3a3.png)

**Comment by sanderdatema** [comment]
You're right, my bad. I didn't have any scenes in my configuration, so you're plugin was smart enough to not show the option.
Sorry and thanks for this very well made plugin!
