### ISSUE TITLE
Suggestion: stop opening external window by default (PI)

### ISSUE THREAD

**Issue by sanderdatema** [cgiesche/streamdeck-homeassistant#52]
I like to move buttons around a lot, but thi splugin opens the settings window every time I select a button in the configuration. It makes the proces very slow an tedious. Would it be possible to only open the settings when pressing a button (like Elgato's example plugin has)?

**Comment by melmatsuoka** [comment]
Seconding this.

**Comment by cgiesche** [comment]
Settings will show in the integrated view only after the next release. The "open in popup window" feature will maybe return at a later point.
