### ISSUE TITLE
Title disappears on experimental button

### ISSUE THREAD

**Issue by linickx** [cgiesche/streamdeck-homeassistant#55]
Hello,

The new on/off icons is cool! Is it just me that the title vanishes when the icon toggles?

Off: 
![image](https://user-images.githubusercontent.com/649661/132137095-0d9a02ac-9c81-43a9-ba1e-ce30a304eab3.png)

On: 
![image](https://user-images.githubusercontent.com/649661/132137103-8d38c31d-165e-43ed-834f-5d174a11aae6.png)

Domain: Light
Service: Toggle

Title cleared, custom set to friendly name.

![image](https://user-images.githubusercontent.com/649661/132137156-2aa1cfac-e4d0-4c64-a282-38f15e92db57.png)

(Default Settings act the same)

Icons used are from material design: [Bulb-Outline](https://materialdesignicons.com/icon/lightbulb-outline) & [Bulb-on.](https://materialdesignicons.com/icon/lightbulb-on)

**Comment by cgiesche** [comment]
Hi,

i can reproduce this issue. It seems like StreamDeck ignores the "setTitle" command, when the icon state is set to 1 (on). Debugging output shows, that my plugin sets the title in both cases:

Switching off:
![image](https://user-images.githubusercontent.com/5123180/132140624-e1c7f21d-4aa2-4920-a64d-53c61c623b39.png)

Switching on:
![image](https://user-images.githubusercontent.com/5123180/132140640-dd7018e3-a52f-40e2-86c2-0207e20fcf06.png)

I will take a closer look, but I think this issue may be "unfixable" (from plugin side of view).

**Comment by cgiesche** [comment]
Hmm, second look:
![image](https://user-images.githubusercontent.com/5123180/132140759-b163bfcb-9e6c-4efa-a0c9-99d615886d01.png)
Suddenly, a suspicious "state: 0" appears in setTitle call, when state should be 1...

**Comment by linickx** [comment]
Hi @cgiesche - Can confirm this is fixed in 1.5.1 🙏🏼
