### ISSUE TITLE
Weather entity showing Celsius symbol with Fahrenheit temp

### ISSUE THREAD

**Issue by sethmayer** [cgiesche/streamdeck-homeassistant#60]
streamdeck-homeassistant-55/Home Assistant core-2021.11.5

Weather on the server side is set to Fahrenheit but it seems the celcius symbol is hard coded into the Weather entity button. Data is showing up correctly. If I attempt {{unit_of_measurement}} as a custom label nothing resolves.

**Comment by cgiesche** [comment]
Thank you for your report. 
I can confirm that "°C" is the hardcoded default unit for weather entities. Home Assistant does not provide anything like "unit_of_measurement" for weather entities.
You can override the default value with the following config:
![image](https://user-images.githubusercontent.com/5123180/144720981-1a78d151-c583-432f-ac44-54f898fa272a.png)
As long as the temperature unit is not part of the entity's status data, i am not able to fix this issue :(
