### ISSUE TITLE
Option to show "last changed" time

### ISSUE THREAD

**Issue by garv3** [cgiesche/streamdeck-homeassistant#61]
It would be awesome to have a nunjucks variable to show the "last_changed" and "last_updated" time values of entities.
This information is not part of the state attributes but should be accessible.

Is it possible to add this?

**Comment by cgiesche** [comment]
Hi garv3,

after 2 minutes of quick research, i think this should be possible and not very hard to implement. I will add those two values soon™.

**Comment by garv3** [comment]
Awesome!
Yes, should be easy. They are on the same level as the "attributes" object.
What would make it even better would be an option to show those as a delta like "5 min. ago". The only problem could be time zones.

**Comment by cgiesche** [comment]
Hi,

thanks to @ToBiDi0410 for fixing this: #67. This will be part of Release (1.5.3). Maybe nunjucks allows formatting dates like "5 min ago".

**Comment by garv3** [comment]
Awesome! Thank you 👍
