### ISSUE TITLE
possible to dim light?

### ISSUE THREAD

**Issue by JonGilmore** [cgiesche/streamdeck-homeassistant#65]
I'm struggling to figure this out; is it possible to turn on a light to a certain percentage? I assume I'd use something like this in the `Service Data JSON`, but it doesn't seem to work:

```
[
  {
    "service": "light.turn_on",
    "target": {
      "entity_id": "light.office_cans"
    },
    "data": {
      "brightness": 50
    }
  }
]
```

Is this possible? Thanks!

**Comment by cgiesche** [comment]
Yes, it is possible. You may try
`{
      "brightness": 50
    }`. The json text box only contains the data part of your json.

**Comment by JonGilmore** [comment]
🤦  
boy, its obvious now, haha. thanks!
