### ISSUE TITLE
Sperate icons for switches

### ISSUE THREAD

**Issue by rvst1104** [cgiesche/streamdeck-homeassistant#7]
Hi,

first of all thanks you so much for this integration! Works great for me so far and one step further to retire my Homey 😄 
There is one thing that would be very useful for me.
Other StreamDeck Apps have the abilty to set an icon for when the switch is turned on and a different icon for when its turned off (see Screenshots attached).
<img width="84" alt="2021-02-04 01_01_26-Stream Deck" src="https://user-images.githubusercontent.com/64125185/106825352-feb62c00-6684-11eb-8688-91c41c3bc54c.png">
<img width="95" alt="2021-02-04 01_01_19-Stream Deck" src="https://user-images.githubusercontent.com/64125185/106825353-ff4ec280-6684-11eb-9fd8-7289ae4648ad.png">

Would be really helpful to also have this option with your App.

Thanks in advance!

Regards
rvst

**Comment by cgiesche** [comment]
Hi rvst,

first of all, thank you for your suggestion! I already thought about something similar, but came to the decision to not implement this kind of feature (yet). The main difficulty in my plugin is that it supports many different entity types and generates images (svg) dynamically. Mixing this dynamic approach with the configuration approach *could* work, but would make the implementation much less generic. In addition, you can only configure two different images, most likely this would be an "on-image" and an "off-image". How would i decide, where to use this image? Only on Switches? Or Lights? Boolean sensors?

Maybe i will come back to this idea sometime.

**Comment by EpicLPer** [comment]
Not sure if you'll still see this @cgiesche but maybe you can make 2 different "Home Assistant Entities" for this in the right panel to pick from. One that has this kind of function and one that's just the normal standard thing we have right now, could potentially solve this issue.

**Comment by cgiesche** [comment]
I am considering to consider to take a look at what could be done, if i would decide to try implement this ;). This would of course only work for switches and lights, and i would not be able to add "labels" to the image.

\*considering\*

**Comment by Leolele99** [comment]
Sorry to open this up again.

One possible solution for this problem, together with fixing the more than one icon problem, could be providing text fields where users can specify the path to the icon they want. 
For every icon you dynamically create, a new box could appear on your custom setup window, where one could provide the offline path or link to override that specific generated image.
Could that work?

One reference for this would be BarRaiders OBSTools where he uses a similar method.

**Comment by cgiesche** [comment]
Hey Leolele99,

of course, allowing the user to define the path to an icon sounds like the easy way to go. Unfortunatelly I choose the "web-way" (JavaScript) to implement the plugin. With that approach, i am very limited when it comes to accessing resources (files) from the user's computer (in fact, i think i can not access them at all, it's a safety feature). I think even "fake" file uploads (like in normal websites) would not work.
If i would be able to get the image data, overlaying them with labels or the "dot" would be quite easy. As far as i can see, the BarRaider plugin(s) are native .NET applications which are much less limited compared to javascript.

My current approach is to use the built in custom icon selection. The drawback of this approach is, that i can not access the icon content from my code. I can only tell streamdeck to switch to user-icon 0 or 1. No chance to manipulate that image.

I added a second button type that allowes to choose custom icons for "on/off" entities (it feels hacky and i dont like it, but it seems to work). Maybe i can release a preview this weekend:

![image](https://user-images.githubusercontent.com/5123180/125121353-17bf7f00-e0f4-11eb-8be0-3dd1f8f66674.png)

**Comment by Leolele99** [comment]
Can you access normal web image links?
While your workaround probably is more than enough for me, I'd still love to see an option to just plug in direct image links to imgur or something, if that is at all possible.

Thanks for your quick answer anyways, looking forward to the preview!

**Comment by cgiesche** [comment]
> Can you access normal web image links?
> While your workaround probably is more than enough for me, I'd still love to see an option to just plug in direct image links to imgur or something, if that is at all possible.

This may be possible. I will give it a try.

> Edit: Idk if this is the right issue for it, but maybe you could add an option to change the colours of the default sliders/icons? That would probably also be enough for many already.

With the last update, i already prepared the code for customizable colors. It will be available soom(tm). I will create a new ticket for this.

**Comment by cgiesche** [comment]
Experimental Version will be part of next release.
