### ISSUE TITLE
Change icon from slider?

### ISSUE THREAD

**Issue by wkearney99** [cgiesche/streamdeck-homeassistant#73]
Is there a way to change the icon shown from a slider off/slider on(yellow) to other toggling icons?  Like a hollow/lit lightbulb?

**Comment by cgiesche** [comment]
I had a version with different icons for switches (current slider) and lights (bulbs) but it did not look good on the button (too small). Making the icons for buttons configurable would be great, but I currently have very little time to implement new features (plus this feature "done right" is not trivial).
I will keep this issue open as an idea, but please do not expect to get this feature in the near future.
