### ISSUE TITLE
Elgato streamdeck store

### ISSUE THREAD

**Issue by nicolap75** [cgiesche/streamdeck-homeassistant#74]
Why not publish this fabulous and useful plugin in the official elgato streamdeck store?

Thx N.

**Comment by cgiesche** [comment]
I will check, if there is a way to get the plugin to the store. When i released the first version, adding plugins to the store was a manual "email" process, which i did not like :D

**Comment by nicolap75** [comment]
They are working on a portal but at the moment it still seems to be by e-mail.

(End of page) [](https://developer.elgato.com/documentation/stream-deck/sdk/distribution/)

**Comment by cgiesche** [comment]
Tanks for info! I will check, if they accept my plugin :)

**Comment by cgiesche** [comment]
Update: I have to do some minor changes to the plugin's internal struture, before it can be added to the store.

```
Unfortunately we can't upload your plugin to the store as is.
Please make sure you named your plugin and manifest properly and used a proper identifier for the plugin as described here:

https://developer.elgato.com/documentation/stream-deck/sdk/plugin-architecture/#plugin-unique-identifier

otherwise our backend can't handle it.

Also please avoid version-information in the plugin's id (like in: StreamDeckHomeAssistant-1.5.6.streamDeckPlugin)

A proper plugin id would be 'com.mycompany.myplugin.streamDeckPlugin'.

Please check your plugin and simply come back here when done.
```

**Comment by cgiesche** [comment]
Whooop whooop. Prepare to re-configure all of your buttons as the configuration will be lost after those changes. \o/

**Comment by nicolap75** [comment]
> Update: I have to do some minor changes to the plugin's internal struture, before it can be added to the store.
> 
> ```
> Unfortunately we can't upload your plugin to the store as is.
> Please make sure you named your plugin and manifest properly and used a proper identifier for the plugin as described here:
> 
> https://developer.elgato.com/documentation/stream-deck/sdk/plugin-architecture/#plugin-unique-identifier
> 
> otherwise our backend can't handle it.
> 
> Also please avoid version-information in the plugin's id (like in: StreamDeckHomeAssistant-1.5.6.streamDeckPlugin)
> 
> A proper plugin id would be 'com.mycompany.myplugin.streamDeckPlugin'.
> 
> Please check your plugin and simply come back here when done.
> ```

That sounds like great news. Thx

**Comment by cgiesche** [comment]
What does not sound like great news: https://github.com/cgiesche/streamdeck-homeassistant/releases/tag/2.0.0 ;)

**Comment by nicolap75** [comment]
Very nice.
THX !!!

**Comment by Buntje** [comment]
is it already available in the store? i can't find it there

**Comment by cgiesche** [comment]
Nope. I am waiting for feedback from elgato.
I will close this issue, when the plugin is available.

For new users: It _may_ work to install the plugin manually for now and then switch to the store version later (just a guess, no guarantee).

**Comment by nvdweem** [comment]
It seems to be there 👍 
![image](https://user-images.githubusercontent.com/830783/155268710-540266dd-6df0-4a87-8c12-a0135e271c8a.png)

**Comment by cgiesche** [comment]
\o/
