### ISSUE TITLE
Consider "paused" media player as "off" from a state perspective

### ISSUE THREAD

**Issue by ybizeul** [cgiesche/streamdeck-homeassistant#75]
Use defined icons for on/off work well, except for media players which are technically "off" when "paused", that way we could have icons representing play state.

**Comment by ybizeul** [comment]
That would probably here, I'll see what I can do https://github.com/cgiesche/streamdeck-homeassistant/blob/9785765e44ec57067019c1e92ac7245114f7c8f5/src/Plugin.vue#L199

**Comment by ybizeul** [comment]
https://github.com/cgiesche/streamdeck-homeassistant/pull/76

**Comment by cgiesche** [comment]
Thank you very much for your contribution! I just created a new release including your changes.
If everything works as expected, feel free to close this issue (i do not have a media player entity ready for testing)

**Comment by ybizeul** [comment]
Done ! Thanks ! I hope we'll have that in the official store
