### ISSUE TITLE
Display Multiple Sensor Values on a single button

### ISSUE THREAD

**Issue by RichardTHF** [cgiesche/streamdeck-homeassistant#83]
Is it possible to display multiple sensor values on a single button, for example I have a 3D Printer connected via the OctoPrint integration, unfrotunatly everything is added as a individual sensor, so octoprint.status and octoprint.jobpercentage are seperate, but it would be great to have them together.

**Comment by cgiesche** [comment]
Hi,

the plugin only allows to display data from a single entity/sensor per button. Collecting values from different entites would be complicated to configure and to implement (as every entity gets separate update messages from Home Assistent, after a value changed).

I guess it should be possible to add a configuration for a "virtual" entity to home assistant that combines data other entities into one. With that, you could show everything that fits on the tiny screens :)

**Comment by RichardTHF** [comment]
makes total sense, I actually managed to do a bodge by creating a template sensor! Thanks for getting back though :)

**Comment by gaborbernat** [comment]
Any pointers on how one can setup this virtual entity? Looked at https://www.home-assistant.io/integrations/group but that adds up the values, would need something that keeps it separate.

**Comment by julianrinaldi** [comment]
For anyone else interested in this, here is a template sensor I made to be able to display values from different entities on a single button with a custom title and custom labels. I used emojis in my template sensor, but this will only work in the custom title field, not for custom labels.

```
- platform: template
  sensors:
    office_apple_tv_plex_sensor:
      friendly_name: Office Apple TV Plex Sensor
      value_template: >-
        {% if state_attr('media_player.plex_julian_rinaldi_office_apple_tv', 'media_content_type') == 'tvshow' %}
          📺 Plex
        {% elif state_attr('media_player.plex_julian_rinaldi_office_apple_tv', 'media_content_type') == 'movie' %}
          🎬 Plex
        {% elif state_attr('media_player.plex_julian_rinaldi_office_apple_tv', 'media_content_type') == 'music' %}
          🎵 Plex
        {% else %}
          
        {% endif %}
      attribute_templates:
        playing: >-
          {% if is_state('media_player.office_apple_tv', 'playing') %}
            Playing
          {% elif is_state('media_player.office_apple_tv', 'paused') %}
            Paused
          {% else %}
            
          {% endif %}
        series: "{{ state_attr('media_player.plex_julian_rinaldi_office_apple_tv', 'media_series_title') }}"
        title: "{{ state_attr('media_player.plex_julian_rinaldi_office_apple_tv', 'media_title') }}"
```

Then for the custom title field you would put:

{{state}}

And for the custom label field you would put:

{{playing}}
{{series}}
{{title}}

Hope this helps!
