### ISSUE TITLE
Weather temperature always displays °C regardless of unit of measurement.

### ISSUE THREAD

**Issue by ohgodbees** [cgiesche/streamdeck-homeassistant#86]
I have set up the plugin to call the weather (domain) and openweathermap (entity), and it gets the temperature correctly but display the temperature value as being celsius and ignores the unit of measurement. This only seems to happen with openweathermap as I have another sensor that shows correctly with °F after the value.

When I call the API directly (A GET call to /api/states) it displays the right information:

` {
"entity_id": "sensor.openweathermap_temperature",
"state": "27.5",
"attributes": {
"state_class": "measurement",
"unit_of_measurement": "°F",
"attribution": "Data provided by OpenWeatherMap",
"device_class": "temperature",
"friendly_name": "OpenWeatherMap Temperature"
},`

It actually displays the correct temperature, it just puts °C after it on the Stream Deck:

![image](https://user-images.githubusercontent.com/19435367/155581204-80f4c424-7a61-4b93-bcaa-a71dcb244095.png)

**Comment by cgiesche** [comment]
Thank you for your feedback.

It is a hardcoded problem an should be easy to solve:
https://github.com/cgiesche/streamdeck-homeassistant/blob/e3ac12840668e54683ad4a55521637b86a5763e7/src/modules/plugin/entityButtonImageFactory.js#L285
