### ISSUE TITLE
Custom labels are rendered below icon

### ISSUE THREAD

**Issue by tuxtof** [cgiesche/streamdeck-homeassistant#87]
When i use custom icon on an Entity with custom labels , labels are hidden

before
![image](https://user-images.githubusercontent.com/180613/155770220-80ce90c7-d7a0-4a9a-a733-9d2964edf619.png)

after
![image](https://user-images.githubusercontent.com/180613/155770285-804ed603-4dfb-4b93-9711-754819b791ba.png)

**Comment by cgiesche** [comment]
Hi,

due to technical limitations of the plugin API, it is not possible for me to draw labels on custom icons. The only thing that will still be rendered, is the title which may contain variables.

**Comment by tuxtof** [comment]
oh bad news, in all case thanks for the great work
