### ISSUE TITLE
Garage door/button status

### ISSUE THREAD

**Issue by Nexetion** [cgiesche/streamdeck-homeassistant#88]
My garage door is a cover and I'm trying to use the entity (custom icons) to open/close my garage door (toggle service) but when I press the button it opens but the state of the button will switch back to the off status which doesn't make any sense and for the life of my I can't figure out how to make this work like a switch

**Comment by cgiesche** [comment]
Currently, only entity states "on" and "playing" are interpreted as "on"-states. Maybe your garage door entity reports a different state string?  If you can find out and tell me which state the entity is in, when the garage door ist open, i can add it to the list of "on"-states.

**Comment by burgviking2012** [comment]
@cgiesche My garage doors are both type "cover" (https://www.home-assistant.io/integrations/cover/), which has default states "open" and "closed". This would also really help me, would be great if you wanted to add "open" as a valid "on" state!

**Comment by ibmlmjm** [comment]
I also really need this feature for all my shades(13 of them).  I have the same issue with the open and closed

Thank You!

Michael

Michael

**Comment by zarmstrong** [comment]
I'd like to add two more states -- opening and closing.

arrow-up-box and arrow-down-box would be the mdi icons for those states.

**Comment by zellers** [comment]
I'd also like to add two more states (for device_tracker / Person)
home -> ON
not_home -> OFF

https://www.home-assistant.io/integrations/person/

**Comment by wivaku** [comment]
and for locks: `locked` and `unlocked`.

In general, probably best to add configuration fields:
- `on`: list of values that should be considered on
- `off`: list of values that should be considered off

**Comment by cgiesche** [comment]
Will be part of next release.
