### ISSUE TITLE
Custom icon based on entity state

### ISSUE THREAD

**Issue by legrego** [cgiesche/streamdeck-homeassistant#89]
Is there a way to provide a custom icon based on an entity's current state?

For example, I have a button assigned to a `person` entity, and I'm using the custom label to show their current location. What I would like to do is assign each zone to a specific icon. Perhaps I'd show a picture of our house when they are home, and a different icon if they're at work, school, etc. This doesn't seem possible with the "custom icon" option, as that seems to be tailored to binary on/off states

**Comment by cgiesche** [comment]
Hi,

unfortunately this is not possible due to API restrictions. StreamDeck is limited to at most two icons per button :(

**Comment by legrego** [comment]
Ah that's a shame. Thanks for following up with me, and I really appreciate your work on this plugin!
