### ISSUE TITLE
Text only button

### ISSUE THREAD

**Issue by ybizeul** [cgiesche/streamdeck-homeassistant#96]
I'm basically trying to do this, which currently works with a node-red integration, it would make more sense to get that from HA directly :
![image](https://user-images.githubusercontent.com/182035/167287382-5e6f8928-cd0a-414c-a564-a88c13aa2290.png)

Closest I can get is this, but I'd like to remove the icon :
![image](https://user-images.githubusercontent.com/182035/167287405-146c2f46-048b-400b-b625-9f867f07d750.png)

Maybe I missed something ?

**Comment by cgiesche** [comment]
Hmm, i think this is not possible (yet). I will add a "hide icon" option in the button configuration.

**Comment by cgiesche** [comment]
Ok, just a quick update. This is the closest, I can get:
![image](https://user-images.githubusercontent.com/5123180/168466535-6c73d8a9-544b-4d69-b342-4f32c77b00f6.png)

So just adding a "hide icon" should be enough to get exactly, what you need.

**Comment by ybizeul** [comment]
Exactly, the fact it displays the default icon can actually be a problem.
