### ISSUE TITLE
Weird text displayed below icon

### ISSUE THREAD

**Issue by ybizeul** [cgiesche/streamdeck-homeassistant#97]
Something seems to be displayed below some icons. In this case it's a scene entity

![image](https://user-images.githubusercontent.com/182035/168489105-529e50a0-733a-4e58-95f7-9406cdd596f4.png)

Could be a timestamp ?

**Comment by cgiesche** [comment]
Yes. Every entity by default shows the content of the "state" variable. I think scenes have a timestamp when they were last activated. You can hide (or change it to something else with the custom labels option.

**Comment by ybizeul** [comment]
Ah, yes indeed, closing this, if you implement "hide icon" I shouldbe able to set the icon StreamDeck side and center it. Thanks !
